// GENERATED by tools/shaderlib_extract.py --emit-header. DO NOT EDIT.
//
// Every cooked FTAAStandaloneCS permutation in the game build, fnv1a64 over the DXBC
// container exactly as ReShade hashes it at init_pipeline. Membership here is the
// hash half of TAA identification (CLAUDE.md #2.3); the structural signature is the
// other half and neither is sufficient alone.
//
// Source: GlobalShaderCache-PCD3D_SM5.bin (14055339 bytes,
//         sha1 3e90f2558e92d0643ad3107bd3638acfce3d9fab), FTAAStandaloneCS section #189,
//         27 permutations. Regenerate after a game update:
//   pakextract.py <pak> out GlobalShaderCache-PCD3D_SM5 --raw
//   oodle_unblock.py out/...json out/...raw cache.bin <oozraw>
//   shaderlib_extract.py cache.bin --emit-header src/core/taa_hashes.hpp
#pragma once

#include <cstddef>
#include <cstdint>

namespace stray_dlss {

inline constexpr std::uint64_t kKnownTaaHashes[] = {
	0x29ea36c96fe60520ull,
	0x2d67549bedef2c0aull,
	0x32b813bbcdde4324ull,
	0x3c75309bcbd07436ull,
	0x42a78cac98275f21ull,
	0x4a1ef369c916a2d4ull,
	0x4b56628a3622dc50ull,
	0x4e0c16e4a90b943aull,
	0x5165782d00fcf560ull,
	0x53597d351a367e56ull,
	0x5455d8748194d2c4ull,
	0x54b77533f6ee0b81ull,
	0x7c16dedced384e9full,
	0x81beb1aa459905fcull,
	0x876f85dfc23213d0ull,
	0x901e041a7cadc9dbull,
	0x9ee6fc84312c1710ull,
	0xa09c3bb4a8e71fc3ull,
	0xa364fdf199452df1ull,
	0xaba0310973451f34ull,
	0xac88ab6814d3dc04ull,
	0xc04977afd6cb75f5ull,
	0xd2e4d8c23c362ed1ull,
	0xd4b8dfa8fdfb8de1ull,
	0xe14e7fc8d0db9b0full,
	0xe2919abc4a7cb62bull,
	0xf04d74c48219060aull,
};

} // namespace stray_dlss
