#include "gbuffer_resolve.hpp"

#include "core/ring.hpp"
#include "log.hpp"

#include <d3d12.h>

#include <gbuffer_resolve.h> // g_gbuffer_resolve_dxbc, generated by fxc at build time

#include <cstdio>
#include <cstring>
#include <mutex>
#include <vector>

namespace stray_dlss::gbr {
namespace {

// Matches the cbuffer in shaders/gbuffer_resolve.hlsl. Same order deliberately; a mismatch
// produces plausible-looking but wrong guides rather than an error. (mv_resolve precedent)
struct Params
{
	float world_to_view_row0[4];
	float world_to_view_row1[4];
	float world_to_view_row2[4];
	float render_size[2];
	float view_rect_min[2];
	float proj00;
	float proj11;
	std::uint32_t c_view_decodes_srgb;
	std::uint32_t padding;
};
static_assert(sizeof(Params) % 16 == 0, "constant buffer must be 16-byte aligned");

// This module's frame slice: t0 GBufferA, t1 GBufferB, t2 GBufferC, then u0..u3 outputs.
// Wider than mv_resolve's, so it uses ring::descriptor_offset_n with its own width.
constexpr UINT kSrvCount = 3;
constexpr UINT kUavCount = 4;
constexpr UINT kDescriptorsPerFrame = kSrvCount + kUavCount;
constexpr UINT kFrameCount = ring::kFrameCount;
constexpr UINT kDescriptorCount = kDescriptorsPerFrame * kFrameCount;

// Output formats. Rationale in shaders/gbuffer_resolve.hlsl's header (the RR guide's
// format table, RESEARCH-RR-GBUFFER.md §2.2, restricted to D3D12's GUARANTEED
// typed-UAV-store formats so the store cannot silently no-op anywhere).
constexpr DXGI_FORMAT kNormalRoughnessFormat = DXGI_FORMAT_R16G16B16A16_FLOAT;
constexpr DXGI_FORMAT kRoughnessFormat = DXGI_FORMAT_R16_FLOAT;
constexpr DXGI_FORMAT kAlbedoFormat = DXGI_FORMAT_R8G8B8A8_UNORM;
// Bytes per pixel across all four outputs (8 + 2 + 4 + 4), for the stats accounting.
constexpr std::uint64_t kOutputBytesPerPixel = 18;

struct State
{
	ID3D12Device *device = nullptr;

	ID3D12RootSignature *root_signature = nullptr;
	ID3D12PipelineState *pso = nullptr;
	ID3D12DescriptorHeap *heap = nullptr; // shader-visible CBV/SRV/UAV
	ID3D12Resource *constants = nullptr;  // upload heap, kFrameCount * aligned Params
	ID3D12Resource *out_normal_roughness = nullptr;
	ID3D12Resource *out_roughness = nullptr;
	ID3D12Resource *out_diffuse = nullptr;
	ID3D12Resource *out_specular = nullptr;

	UINT descriptor_size = 0;
	UINT constant_stride = 0;
	std::uint64_t frame = 0;

	// Allocated size — grow-only, like mv_resolve; the shader bounds itself by RenderSize.
	std::uint32_t width = 0;
	std::uint32_t height = 0;

	struct Retired
	{
		ID3D12DescriptorHeap *heap = nullptr;
		ID3D12Resource *constants = nullptr;
		ID3D12Resource *outputs[4] = {};
		std::uint64_t retire_frame = 0;
		std::uint64_t bytes = 0;
	};
	std::vector<Retired> retired;

	// Inputs AddRef'd at record() and released only once the GPU can no longer be reading
	// them — the mv_resolve keep-alive, for the same measured Xid-109 reason.
	struct LiveInput
	{
		ID3D12Resource *a = nullptr;
		ID3D12Resource *b = nullptr;
		ID3D12Resource *c = nullptr;
		std::uint64_t frame = 0;
	};
	std::vector<LiveInput> input_keep_alive;

	Stats stats;
	char error[256] = {};
};

State g_state;

void set_error(const char *what, HRESULT hr)
{
	std::snprintf(g_state.error, sizeof(g_state.error), "%s (hr=0x%08x)", what,
		static_cast<unsigned int>(hr));
	STRAY_LOG_ERROR("gbuffer_resolve: %s", g_state.error);
}

template <typename T>
void release(T *&p)
{
	if (p != nullptr)
	{
		p->Release();
		p = nullptr;
	}
}

bool create_root_signature()
{
	D3D12_DESCRIPTOR_RANGE ranges[2] = {};
	ranges[0].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
	ranges[0].NumDescriptors = kSrvCount; // t0 A, t1 B, t2 C
	ranges[0].BaseShaderRegister = 0;
	ranges[0].OffsetInDescriptorsFromTableStart = 0;
	ranges[1].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
	ranges[1].NumDescriptors = kUavCount; // u0..u3 guides
	ranges[1].BaseShaderRegister = 0;
	ranges[1].OffsetInDescriptorsFromTableStart = kSrvCount;

	D3D12_ROOT_PARAMETER params[2] = {};
	params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_CBV;
	params[0].Descriptor.ShaderRegister = 0; // b0
	params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
	params[1].DescriptorTable.NumDescriptorRanges = 2;
	params[1].DescriptorTable.pDescriptorRanges = ranges;

	D3D12_ROOT_SIGNATURE_DESC desc = {};
	desc.NumParameters = 2;
	desc.pParameters = params;
	desc.Flags = D3D12_ROOT_SIGNATURE_FLAG_NONE;

	ID3DBlob *blob = nullptr;
	ID3DBlob *errors = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(&desc, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &errors);
	if (FAILED(hr))
	{
		if (errors != nullptr)
		{
			STRAY_LOG_ERROR("gbuffer_resolve: root signature: %.*s",
				static_cast<int>(errors->GetBufferSize()),
				static_cast<const char *>(errors->GetBufferPointer()));
			errors->Release();
		}
		set_error("D3D12SerializeRootSignature", hr);
		return false;
	}
	if (errors != nullptr)
		errors->Release();

	hr = g_state.device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(),
		IID_PPV_ARGS(&g_state.root_signature));
	blob->Release();

	if (FAILED(hr))
	{
		set_error("CreateRootSignature", hr);
		return false;
	}
	return true;
}

bool create_pipeline()
{
	D3D12_COMPUTE_PIPELINE_STATE_DESC desc = {};
	desc.pRootSignature = g_state.root_signature;
	desc.CS.pShaderBytecode = g_gbuffer_resolve_dxbc;
	desc.CS.BytecodeLength = sizeof(g_gbuffer_resolve_dxbc);

	const HRESULT hr = g_state.device->CreateComputePipelineState(&desc, IID_PPV_ARGS(&g_state.pso));
	if (FAILED(hr))
	{
		set_error("CreateComputePipelineState", hr);
		return false;
	}
	return true;
}

bool create_output(DXGI_FORMAT format, std::uint32_t width, std::uint32_t height,
                   const char *what, ID3D12Resource **out)
{
	D3D12_HEAP_PROPERTIES default_heap = {};
	default_heap.Type = D3D12_HEAP_TYPE_DEFAULT;

	D3D12_RESOURCE_DESC tex = {};
	tex.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
	tex.Width = width;
	tex.Height = height;
	tex.DepthOrArraySize = 1;
	tex.MipLevels = 1;
	tex.Format = format;
	tex.SampleDesc.Count = 1;
	tex.Layout = D3D12_TEXTURE_LAYOUT_UNKNOWN;
	// ALLOW_UNORDERED_ACCESS is not optional; a missing flag on an NGX input/output can
	// produce a black result with no error at all. (docs/RESEARCH.md §3.5)
	tex.Flags = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;

	const HRESULT hr = g_state.device->CreateCommittedResource(&default_heap,
		D3D12_HEAP_FLAG_NONE, &tex, D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr,
		IID_PPV_ARGS(out));
	if (FAILED(hr))
	{
		set_error(what, hr);
		return false;
	}
	return true;
}

bool create_resources(std::uint32_t width, std::uint32_t height)
{
	// Our own shader-visible heap; NGX clobbers whatever heap is bound when it runs.
	D3D12_DESCRIPTOR_HEAP_DESC heap_desc = {};
	heap_desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
	heap_desc.NumDescriptors = kDescriptorCount;
	heap_desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;

	HRESULT hr = g_state.device->CreateDescriptorHeap(&heap_desc, IID_PPV_ARGS(&g_state.heap));
	if (FAILED(hr))
	{
		set_error("CreateDescriptorHeap", hr);
		return false;
	}

	g_state.descriptor_size =
		g_state.device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
	g_state.constant_stride = ring::aligned_constant_stride(sizeof(Params));

	D3D12_HEAP_PROPERTIES upload = {};
	upload.Type = D3D12_HEAP_TYPE_UPLOAD;

	D3D12_RESOURCE_DESC buf = {};
	buf.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
	buf.Width = static_cast<UINT64>(g_state.constant_stride) * kFrameCount;
	buf.Height = 1;
	buf.DepthOrArraySize = 1;
	buf.MipLevels = 1;
	buf.Format = DXGI_FORMAT_UNKNOWN;
	buf.SampleDesc.Count = 1;
	buf.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;

	hr = g_state.device->CreateCommittedResource(&upload, D3D12_HEAP_FLAG_NONE, &buf,
		D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(&g_state.constants));
	if (FAILED(hr))
	{
		set_error("CreateCommittedResource(constants)", hr);
		return false;
	}

	if (!create_output(kNormalRoughnessFormat, width, height,
			"CreateCommittedResource(normal_roughness)", &g_state.out_normal_roughness) ||
		!create_output(kRoughnessFormat, width, height,
			"CreateCommittedResource(roughness)", &g_state.out_roughness) ||
		!create_output(kAlbedoFormat, width, height,
			"CreateCommittedResource(diffuse_albedo)", &g_state.out_diffuse) ||
		!create_output(kAlbedoFormat, width, height,
			"CreateCommittedResource(specular_albedo)", &g_state.out_specular))
		return false;

	// The UAVs never change; each ring slot gets its own copies (indices kSrvCount..+3).
	const D3D12_CPU_DESCRIPTOR_HANDLE base = g_state.heap->GetCPUDescriptorHandleForHeapStart();
	struct
	{
		ID3D12Resource *res;
		DXGI_FORMAT format;
	} const uavs[kUavCount] = {
		{ g_state.out_normal_roughness, kNormalRoughnessFormat },
		{ g_state.out_roughness, kRoughnessFormat },
		{ g_state.out_diffuse, kAlbedoFormat },
		{ g_state.out_specular, kAlbedoFormat },
	};

	for (UINT f = 0; f < kFrameCount; ++f)
	{
		for (UINT i = 0; i < kUavCount; ++i)
		{
			D3D12_UNORDERED_ACCESS_VIEW_DESC uav_desc = {};
			uav_desc.Format = uavs[i].format;
			uav_desc.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;

			D3D12_CPU_DESCRIPTOR_HANDLE dest = base;
			dest.ptr += ring::descriptor_offset_n(f, kDescriptorsPerFrame, kSrvCount + i,
				g_state.descriptor_size);
			g_state.device->CreateUnorderedAccessView(uavs[i].res, nullptr, &uav_desc, dest);
		}
	}

	g_state.width = width;
	g_state.height = height;
	++g_state.stats.resource_sets_created;
	return true;
}

// The SRV format to view a G-buffer input through, per ROLE.
//
// GBufferC is sRGB-STORED (TexCreate_SRGB — RESEARCH-RR-GBUFFER.md §1.2/§2.4) and RR
// wants LINEAR albedo, so its view must decode: a typeless 8-bit resource gets the
// *_SRGB view. GBufferB stores raw material scalars and must NEVER be viewed as sRGB.
// A fully typed resource keeps its own format — no cross-family guessing — and the
// caller is told whether the C view decodes (the shader decodes in code when it does
// not). Wrong sRGB handling here is a silently-dimmed albedo, not an error.
DXGI_FORMAT srv_format_for_role(DXGI_FORMAT resource_format, bool is_c_role,
                                bool *c_view_decodes_srgb)
{
	switch (resource_format)
	{
	case DXGI_FORMAT_B8G8R8A8_TYPELESS:
		if (is_c_role)
		{
			*c_view_decodes_srgb = true;
			return DXGI_FORMAT_B8G8R8A8_UNORM_SRGB;
		}
		return DXGI_FORMAT_B8G8R8A8_UNORM;
	case DXGI_FORMAT_R8G8B8A8_TYPELESS:
		if (is_c_role)
		{
			*c_view_decodes_srgb = true;
			return DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
		}
		return DXGI_FORMAT_R8G8B8A8_UNORM;
	// Fully typed sRGB: the view decodes by construction.
	case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
	case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
		if (is_c_role)
			*c_view_decodes_srgb = true;
		return resource_format;
	// Fully typed UNORM: viewed raw; the C role decodes sRGB in the shader instead.
	case DXGI_FORMAT_R10G10B10A2_TYPELESS:
		return DXGI_FORMAT_R10G10B10A2_UNORM;
	default:
		return resource_format;
	}
}

// Builds THIS frame's SRVs for the game's G-buffers, straight into our own heap — never a
// descriptor copy out of the game's shader-visible heap (illegal as a copy source, #654;
// CLAUDE.md §5) and always from pointers the caller liveness-checked THIS dispatch.
// Returns whether the C-role view decodes sRGB, for the constant buffer.
bool create_srvs(UINT slot, ID3D12Resource *a, ID3D12Resource *b, ID3D12Resource *c)
{
	const D3D12_CPU_DESCRIPTOR_HANDLE base = g_state.heap->GetCPUDescriptorHandleForHeapStart();

	// Log every distinct resource once, immediately BEFORE viewing it, so a stale-pointer
	// fault inside GetDesc/CreateShaderResourceView names its resource. (mv_resolve
	// precedent; the vkCreateImageView 0xc0000005 lesson.)
	const auto note = [](const char *what, ID3D12Resource *res) {
		static std::mutex m;
		static ID3D12Resource *seen[8] = {};
		static unsigned n = 0;
		{
			std::lock_guard<std::mutex> lock(m);
			for (unsigned i = 0; i < n; ++i)
				if (seen[i] == res)
					return;
			if (n < 8)
				seen[n++] = res;
		}
		const D3D12_RESOURCE_DESC d = res->GetDesc();
		STRAY_LOG_INFO("gbuffer_resolve: about to view %s %p: fmt=%d %llux%u flags=0x%x",
			what, static_cast<void *>(res), static_cast<int>(d.Format),
			static_cast<unsigned long long>(d.Width), d.Height,
			static_cast<unsigned>(d.Flags));
	};

	bool c_srgb = false;
	struct
	{
		const char *what;
		ID3D12Resource *res;
		bool is_c;
	} const inputs[kSrvCount] = {
		{ "GBufferA", a, false },
		{ "GBufferB", b, false },
		{ "GBufferC", c, true },
	};

	for (UINT i = 0; i < kSrvCount; ++i)
	{
		note(inputs[i].what, inputs[i].res);
		const D3D12_RESOURCE_DESC d = inputs[i].res->GetDesc();

		D3D12_SHADER_RESOURCE_VIEW_DESC srv = {};
		srv.Format = srv_format_for_role(d.Format, inputs[i].is_c, &c_srgb);
		srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
		// A multisampled resource needs a TEXTURE2DMS view (mv_resolve lesson); the
		// G-buffers are never MSAA in this title, but the guard costs nothing.
		srv.ViewDimension = d.SampleDesc.Count > 1 ? D3D12_SRV_DIMENSION_TEXTURE2DMS
		                                           : D3D12_SRV_DIMENSION_TEXTURE2D;
		srv.Texture2D.MipLevels = 1;

		D3D12_CPU_DESCRIPTOR_HANDLE dest = base;
		dest.ptr += ring::descriptor_offset_n(slot, kDescriptorsPerFrame, i,
			g_state.descriptor_size);
		g_state.device->CreateShaderResourceView(inputs[i].res, &srv, dest);
	}

	return c_srgb;
}

void retire_expired()
{
	for (auto it = g_state.retired.begin(); it != g_state.retired.end();)
	{
		if (!ring::is_safe_to_release(g_state.frame, it->retire_frame))
		{
			++it;
			continue;
		}
		release(it->heap);
		release(it->constants);
		for (auto *&r : it->outputs)
			release(r);
		it = g_state.retired.erase(it);
		++g_state.stats.resource_sets_released;
		g_state.stats.live_retired = static_cast<std::uint32_t>(g_state.retired.size());
	}
}

} // namespace

const char *last_error() { return g_state.error; }

const Stats &stats()
{
	g_state.stats.live_retired = static_cast<std::uint32_t>(g_state.retired.size());
	std::uint64_t bytes = 0;
	if (g_state.out_normal_roughness != nullptr)
		bytes += static_cast<std::uint64_t>(g_state.width) * g_state.height * kOutputBytesPerPixel;
	for (const auto &r : g_state.retired)
		bytes += r.bytes;
	g_state.stats.bytes_live = bytes;
	return g_state.stats;
}

bool is_ready()
{
	return g_state.pso != nullptr && g_state.out_normal_roughness != nullptr;
}

ID3D12Resource *normals_roughness() { return g_state.out_normal_roughness; }
ID3D12Resource *roughness() { return g_state.out_roughness; }
ID3D12Resource *diffuse_albedo() { return g_state.out_diffuse; }
ID3D12Resource *specular_albedo() { return g_state.out_specular; }

bool initialise(ID3D12Device *device, std::uint32_t width, std::uint32_t height)
{
	if (device == nullptr || width == 0 || height == 0)
		return false;

	// GROW-ONLY, exactly like mv_resolve and for the measured reason: reallocation churn
	// during loading orphaned GPU-visible resources and OOM'd the machine. A smaller frame
	// dispatches over part of the textures.
	if (g_state.device != device)
	{
		shutdown();
		g_state.device = device;
	}

	const bool fits = width <= g_state.width && height <= g_state.height;
	if (fits && is_ready())
		return true;

	if (!fits && is_ready())
	{
		State::Retired r;
		r.heap = g_state.heap;
		r.constants = g_state.constants;
		r.outputs[0] = g_state.out_normal_roughness;
		r.outputs[1] = g_state.out_roughness;
		r.outputs[2] = g_state.out_diffuse;
		r.outputs[3] = g_state.out_specular;
		r.retire_frame = g_state.frame;
		r.bytes = static_cast<std::uint64_t>(g_state.width) * g_state.height *
			kOutputBytesPerPixel;
		g_state.retired.push_back(r);
		++g_state.stats.resource_sets_retired;
		g_state.stats.live_retired = static_cast<std::uint32_t>(g_state.retired.size());

		g_state.heap = nullptr;
		g_state.constants = nullptr;
		g_state.out_normal_roughness = nullptr;
		g_state.out_roughness = nullptr;
		g_state.out_diffuse = nullptr;
		g_state.out_specular = nullptr;

		width = width > g_state.width ? width : g_state.width;
		height = height > g_state.height ? height : g_state.height;
	}

	if (g_state.root_signature == nullptr && !create_root_signature())
		return false;
	if (g_state.pso == nullptr && !create_pipeline())
		return false;
	if (g_state.heap == nullptr && !create_resources(width, height))
		return false;

	STRAY_LOG_INFO("gbuffer_resolve ready: normals RGBA16F + roughness R16F + albedos "
		"RGBA8 at %ux%u", width, height);
	return true;
}

void shutdown()
{
	for (auto &r : g_state.retired)
	{
		release(r.heap);
		release(r.constants);
		for (auto *&o : r.outputs)
			release(o);
	}
	g_state.retired.clear();

	for (auto &li : g_state.input_keep_alive)
	{
		if (li.a != nullptr)
			li.a->Release();
		if (li.b != nullptr)
			li.b->Release();
		if (li.c != nullptr)
			li.c->Release();
	}
	g_state.input_keep_alive.clear();

	release(g_state.out_specular);
	release(g_state.out_diffuse);
	release(g_state.out_roughness);
	release(g_state.out_normal_roughness);
	release(g_state.constants);
	release(g_state.heap);
	release(g_state.pso);
	release(g_state.root_signature);
	g_state.device = nullptr;
	g_state.width = 0;
	g_state.height = 0;
}

void transition_outputs(ID3D12GraphicsCommandList *cmd, bool to_shader_resource)
{
	if (cmd == nullptr || !is_ready())
		return;

	ID3D12Resource *const outputs[kUavCount] = {
		g_state.out_normal_roughness,
		g_state.out_roughness,
		g_state.out_diffuse,
		g_state.out_specular,
	};

	D3D12_RESOURCE_BARRIER barriers[kUavCount] = {};
	for (UINT i = 0; i < kUavCount; ++i)
	{
		barriers[i].Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
		barriers[i].Transition.pResource = outputs[i];
		barriers[i].Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
		barriers[i].Transition.StateBefore = to_shader_resource
			? D3D12_RESOURCE_STATE_UNORDERED_ACCESS
			: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
		barriers[i].Transition.StateAfter = to_shader_resource
			? D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE
			: D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
	}
	cmd->ResourceBarrier(kUavCount, barriers);
}

bool record(ID3D12GraphicsCommandList *cmd, const ResolveInputs &in, int dispatch_mode)
{
	if (cmd == nullptr || !is_ready() || in.gbuffer_a == 0 || in.gbuffer_b == 0 ||
		in.gbuffer_c == 0)
		return false;

	const UINT slot = ring::slot_for_frame(g_state.frame);
	g_state.frame++;

	auto *res_a = reinterpret_cast<ID3D12Resource *>(in.gbuffer_a);
	auto *res_b = reinterpret_cast<ID3D12Resource *>(in.gbuffer_b);
	auto *res_c = reinterpret_cast<ID3D12Resource *>(in.gbuffer_c);

	{
		State::LiveInput li;
		li.a = res_a;
		li.b = res_b;
		li.c = res_c;
		li.frame = g_state.frame;
		li.a->AddRef();
		li.b->AddRef();
		li.c->AddRef();
		g_state.input_keep_alive.push_back(li);
		for (auto it = g_state.input_keep_alive.begin();
			it != g_state.input_keep_alive.end();)
		{
			if (ring::is_safe_to_release(g_state.frame, it->frame))
			{
				it->a->Release();
				it->b->Release();
				it->c->Release();
				it = g_state.input_keep_alive.erase(it);
			}
			else
				++it;
		}
	}

	// Unconditionally, every frame — no descriptor cache keyed on handle values, for the
	// mv_resolve reason (recycled slots alias destroyed resources).
	const bool c_srgb = create_srvs(slot, res_a, res_b, res_c);

	retire_expired();

	Params params = {};
	for (int r = 0; r < 3; ++r)
	{
		float *row = r == 0 ? params.world_to_view_row0
		           : r == 1 ? params.world_to_view_row1 : params.world_to_view_row2;
		row[0] = in.world_to_view[r][0];
		row[1] = in.world_to_view[r][1];
		row[2] = in.world_to_view[r][2];
		row[3] = 0.0f;
	}
	params.render_size[0] = static_cast<float>(in.render_width);
	params.render_size[1] = static_cast<float>(in.render_height);
	params.view_rect_min[0] = in.view_rect_min[0];
	params.view_rect_min[1] = in.view_rect_min[1];
	params.proj00 = in.proj00;
	params.proj11 = in.proj11;
	params.c_view_decodes_srgb = c_srgb ? 1u : 0u;

	void *mapped = nullptr;
	D3D12_RANGE no_read = { 0, 0 };
	if (FAILED(g_state.constants->Map(0, &no_read, &mapped)) || mapped == nullptr)
		return false;
	const std::size_t cb_offset = ring::constant_offset(slot, g_state.constant_stride);
	std::memcpy(static_cast<uint8_t *>(mapped) + cb_offset, &params, sizeof(params));
	D3D12_RANGE written = { cb_offset, cb_offset + sizeof(params) };
	g_state.constants->Unmap(0, &written);

	// NO BARRIER ON THE INPUTS, AND THAT IS A DELIBERATE UNCONFIRMED ASSUMPTION.
	//
	// We assume the three G-buffers are already in a shader-resource state at this point:
	// the base pass wrote them early in the frame, deferred lighting has read them as SRVs
	// since, and nothing writes them again before post-processing. mv_resolve makes exactly
	// the same assumption about depth and velocity and has been correct on this title for
	// months, which is the whole of the evidence.
	//
	// The alternative — transitioning resources the GAME owns from a state we GUESSED — is
	// strictly worse and this project has already reasoned it through once (CLAUDE.md §5,
	// NgxNRRestoreHistory): after our pair the resource really is in the state we claimed,
	// while UE's own CPU-side tracking still believes whatever it last set, so a wrong
	// constant desynchronises the ENGINE's bookkeeping rather than only ours. vkd3d-proton
	// has no debug layer to object either way.
	//
	// So a wrong assumption here is a wrong READ, not a corrupted engine. What it would look
	// like is garbage or stale guide content — which is exactly what the guide dump
	// (NgxDumpInputs=1, straydlss_rr_normals_*.bin and its DEGENERATE fraction) is there to
	// show. UNCONFIRMED until a run says otherwise.
	cmd->SetComputeRootSignature(g_state.root_signature);
	cmd->SetPipelineState(g_state.pso);

	ID3D12DescriptorHeap *heaps[] = { g_state.heap };
	cmd->SetDescriptorHeaps(1, heaps);

	cmd->SetComputeRootConstantBufferView(0,
		g_state.constants->GetGPUVirtualAddress() + cb_offset);
	D3D12_GPU_DESCRIPTOR_HANDLE table = g_state.heap->GetGPUDescriptorHandleForHeapStart();
	table.ptr += ring::descriptor_offset_n(slot, kDescriptorsPerFrame, 0,
		g_state.descriptor_size);
	cmd->SetComputeRootDescriptorTable(1, table);

	if (dispatch_mode != 0)
	{
		// Over the FRAME's size, not the allocated size (grow-only policy; the shader
		// bounds itself by RenderSize).
		const UINT gx = (dispatch_mode == 1) ? 1u : (in.render_width + 7) / 8;
		const UINT gy = (dispatch_mode == 1) ? 1u : (in.render_height + 7) / 8;
		cmd->Dispatch(gx, gy, 1);

		// NGX reads the guides right afterwards; make the writes visible.
		D3D12_RESOURCE_BARRIER uav_barriers[kUavCount] = {};
		ID3D12Resource *const outputs[kUavCount] = {
			g_state.out_normal_roughness,
			g_state.out_roughness,
			g_state.out_diffuse,
			g_state.out_specular,
		};
		for (UINT i = 0; i < kUavCount; ++i)
		{
			uav_barriers[i].Type = D3D12_RESOURCE_BARRIER_TYPE_UAV;
			uav_barriers[i].UAV.pResource = outputs[i];
		}
		cmd->ResourceBarrier(kUavCount, uav_barriers);
	}

	return true;
}

} // namespace stray_dlss::gbr
