#include "mv_resolve.hpp"

#include "core/view_params.hpp"
#include "log.hpp"

#include <d3d12.h>

#include <mv_resolve.h> // g_mv_resolve_dxbc, generated by fxc at build time

#include <cstdio>
#include <cstring>

namespace stray_dlss::mv {
namespace {

// Matches the cbuffer in shaders/mv_resolve.hlsl. Kept in the same order deliberately; a
// mismatch here produces a plausible-looking but wrong motion field rather than an error.
struct Params
{
	float clip_to_prev_clip[16];
	float render_size[2];
	float view_rect_min[2];
	float buffer_size[2];
	float padding[2];
};
static_assert(sizeof(Params) % 16 == 0, "constant buffer must be 16-byte aligned");

// Descriptor table layout: t0 depth, t1 velocity, u0 output.
constexpr UINT kDescriptorCount = 3;

// The constant buffer is written every frame from the CPU, so it is triple-buffered to avoid
// overwriting data a queued frame is still reading.
constexpr UINT kFrameCount = 3;

struct State
{
	ID3D12Device *device = nullptr;

	ID3D12RootSignature *root_signature = nullptr;
	ID3D12PipelineState *pso = nullptr;
	ID3D12DescriptorHeap *heap = nullptr;      // shader-visible CBV/SRV/UAV
	ID3D12Resource *constants = nullptr;       // upload heap, kFrameCount * aligned Params
	ID3D12Resource *out_mv = nullptr;          // R16G16_FLOAT at render resolution

	UINT descriptor_size = 0;
	UINT constant_stride = 0;
	UINT frame = 0;

	std::uint32_t width = 0;
	std::uint32_t height = 0;

	std::uint64_t last_depth_descriptor = 0;
	std::uint64_t last_velocity_descriptor = 0;

	char error[256] = {};
};

State g_state;

void set_error(const char *what, HRESULT hr)
{
	std::snprintf(g_state.error, sizeof(g_state.error), "%s (hr=0x%08x)", what,
		static_cast<unsigned int>(hr));
	STRAY_LOG_ERROR("mv_resolve: %s", g_state.error);
}

template <typename T>
void release(T *&p)
{
	if (p != nullptr)
	{
		p->Release();
		p = nullptr;
	}
}

bool create_root_signature()
{
	D3D12_DESCRIPTOR_RANGE ranges[2] = {};
	ranges[0].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
	ranges[0].NumDescriptors = 2; // t0 depth, t1 velocity
	ranges[0].BaseShaderRegister = 0;
	ranges[0].OffsetInDescriptorsFromTableStart = 0;
	ranges[1].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
	ranges[1].NumDescriptors = 1; // u0 output
	ranges[1].BaseShaderRegister = 0;
	ranges[1].OffsetInDescriptorsFromTableStart = 2;

	D3D12_ROOT_PARAMETER params[2] = {};
	params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_CBV;
	params[0].Descriptor.ShaderRegister = 0; // b0
	params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
	params[1].DescriptorTable.NumDescriptorRanges = 2;
	params[1].DescriptorTable.pDescriptorRanges = ranges;

	D3D12_ROOT_SIGNATURE_DESC desc = {};
	desc.NumParameters = 2;
	desc.pParameters = params;
	desc.Flags = D3D12_ROOT_SIGNATURE_FLAG_NONE;

	ID3DBlob *blob = nullptr;
	ID3DBlob *errors = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(&desc, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &errors);
	if (FAILED(hr))
	{
		if (errors != nullptr)
		{
			STRAY_LOG_ERROR("mv_resolve: root signature: %.*s",
				static_cast<int>(errors->GetBufferSize()),
				static_cast<const char *>(errors->GetBufferPointer()));
			errors->Release();
		}
		set_error("D3D12SerializeRootSignature", hr);
		return false;
	}
	if (errors != nullptr)
		errors->Release();

	hr = g_state.device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(),
		IID_PPV_ARGS(&g_state.root_signature));
	blob->Release();

	if (FAILED(hr))
	{
		set_error("CreateRootSignature", hr);
		return false;
	}
	return true;
}

bool create_pipeline()
{
	D3D12_COMPUTE_PIPELINE_STATE_DESC desc = {};
	desc.pRootSignature = g_state.root_signature;
	desc.CS.pShaderBytecode = g_mv_resolve_dxbc;
	desc.CS.BytecodeLength = sizeof(g_mv_resolve_dxbc);

	const HRESULT hr = g_state.device->CreateComputePipelineState(&desc, IID_PPV_ARGS(&g_state.pso));
	if (FAILED(hr))
	{
		set_error("CreateComputePipelineState", hr);
		return false;
	}
	return true;
}

bool create_resources(std::uint32_t width, std::uint32_t height)
{
	// Our own shader-visible heap. NGX will clobber whatever heap is bound when it runs, so
	// there is no way to share the game's, and no benefit in trying.
	D3D12_DESCRIPTOR_HEAP_DESC heap_desc = {};
	heap_desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
	heap_desc.NumDescriptors = kDescriptorCount;
	heap_desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;

	HRESULT hr = g_state.device->CreateDescriptorHeap(&heap_desc, IID_PPV_ARGS(&g_state.heap));
	if (FAILED(hr))
	{
		set_error("CreateDescriptorHeap", hr);
		return false;
	}

	g_state.descriptor_size =
		g_state.device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

	// Constant buffer offsets must be 256-byte aligned.
	g_state.constant_stride = (sizeof(Params) + 255) & ~255u;

	D3D12_HEAP_PROPERTIES upload = {};
	upload.Type = D3D12_HEAP_TYPE_UPLOAD;

	D3D12_RESOURCE_DESC buf = {};
	buf.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
	buf.Width = static_cast<UINT64>(g_state.constant_stride) * kFrameCount;
	buf.Height = 1;
	buf.DepthOrArraySize = 1;
	buf.MipLevels = 1;
	buf.Format = DXGI_FORMAT_UNKNOWN;
	buf.SampleDesc.Count = 1;
	buf.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;

	hr = g_state.device->CreateCommittedResource(&upload, D3D12_HEAP_FLAG_NONE, &buf,
		D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(&g_state.constants));
	if (FAILED(hr))
	{
		set_error("CreateCommittedResource(constants)", hr);
		return false;
	}

	D3D12_HEAP_PROPERTIES default_heap = {};
	default_heap.Type = D3D12_HEAP_TYPE_DEFAULT;

	D3D12_RESOURCE_DESC tex = {};
	tex.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
	tex.Width = width;
	tex.Height = height;
	tex.DepthOrArraySize = 1;
	tex.MipLevels = 1;
	// The only motion-vector formats DLSS accepts are RG16_FLOAT and RG32_FLOAT.
	// (docs/RESEARCH.md §3.2)
	tex.Format = DXGI_FORMAT_R16G16_FLOAT;
	tex.SampleDesc.Count = 1;
	tex.Layout = D3D12_TEXTURE_LAYOUT_UNKNOWN;
	// ALLOW_UNORDERED_ACCESS is not optional: without it NGX can return success and write
	// nothing, which shows up as a black image with no error at all. (docs/RESEARCH.md §3.5)
	tex.Flags = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;

	hr = g_state.device->CreateCommittedResource(&default_heap, D3D12_HEAP_FLAG_NONE, &tex,
		D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, IID_PPV_ARGS(&g_state.out_mv));
	if (FAILED(hr))
	{
		set_error("CreateCommittedResource(out_mv)", hr);
		return false;
	}

	// The UAV never changes, so it is written once.
	D3D12_CPU_DESCRIPTOR_HANDLE base = g_state.heap->GetCPUDescriptorHandleForHeapStart();
	D3D12_CPU_DESCRIPTOR_HANDLE uav = base;
	uav.ptr += static_cast<SIZE_T>(2) * g_state.descriptor_size;

	D3D12_UNORDERED_ACCESS_VIEW_DESC uav_desc = {};
	uav_desc.Format = DXGI_FORMAT_R16G16_FLOAT;
	uav_desc.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
	g_state.device->CreateUnorderedAccessView(g_state.out_mv, nullptr, &uav_desc, uav);

	g_state.width = width;
	g_state.height = height;
	return true;
}

// Copies the game's own SRV descriptors into our heap.
//
// This deliberately does NOT recreate the views from resource pointers. ReShade never calls
// destroy_resource_view on D3D12, so its view->resource map can return a pointer to a resource
// the game already destroyed; passing that to CreateShaderResourceView is an access violation,
// and the game rotates its velocity buffer constantly, so it happens within seconds. Copying
// descriptors needs no resource pointer and no format guessing — the game already described
// the view exactly as its own shader reads it. (docs/RESEARCH.md §2.7)
void copy_srvs(std::uint64_t depth_descriptor, std::uint64_t velocity_descriptor)
{
	D3D12_CPU_DESCRIPTOR_HANDLE dest = g_state.heap->GetCPUDescriptorHandleForHeapStart();

	D3D12_CPU_DESCRIPTOR_HANDLE src_depth = {};
	src_depth.ptr = static_cast<SIZE_T>(depth_descriptor);
	g_state.device->CopyDescriptorsSimple(1, dest, src_depth,
		D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

	dest.ptr += g_state.descriptor_size;
	D3D12_CPU_DESCRIPTOR_HANDLE src_velocity = {};
	src_velocity.ptr = static_cast<SIZE_T>(velocity_descriptor);
	g_state.device->CopyDescriptorsSimple(1, dest, src_velocity,
		D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

	g_state.last_depth_descriptor = depth_descriptor;
	g_state.last_velocity_descriptor = velocity_descriptor;
}

} // namespace

const char *last_error() { return g_state.error; }
bool is_ready() { return g_state.pso != nullptr && g_state.out_mv != nullptr; }
ID3D12Resource *output() { return g_state.out_mv; }

bool initialise(ID3D12Device *device, std::uint32_t width, std::uint32_t height)
{
	if (device == nullptr || width == 0 || height == 0)
		return false;

	if (g_state.device == device && g_state.width == width && g_state.height == height &&
		is_ready())
		return true;

	if (g_state.device != device)
	{
		shutdown();
		g_state.device = device;
	}
	else if (g_state.width != width || g_state.height != height)
	{
		// Resolution changed: only the size-dependent resources need rebuilding.
		release(g_state.out_mv);
		release(g_state.heap);
		release(g_state.constants);
	}

	if (g_state.root_signature == nullptr && !create_root_signature())
		return false;
	if (g_state.pso == nullptr && !create_pipeline())
		return false;
	if (g_state.heap == nullptr && !create_resources(width, height))
		return false;

	STRAY_LOG_INFO("mv_resolve ready: R16G16_FLOAT %ux%u", width, height);
	return true;
}

void shutdown()
{
	release(g_state.out_mv);
	release(g_state.constants);
	release(g_state.heap);
	release(g_state.pso);
	release(g_state.root_signature);
	g_state.device = nullptr;
	g_state.width = 0;
	g_state.height = 0;
	g_state.last_depth_descriptor = 0;
	g_state.last_velocity_descriptor = 0;
}

bool record(ID3D12GraphicsCommandList *cmd, const ResolveInputs &in, int dispatch_mode)
{
	if (cmd == nullptr || !is_ready() || in.depth_descriptor == 0 ||
		in.velocity_descriptor == 0 || in.view == nullptr)
		return false;

	if (in.depth_descriptor != g_state.last_depth_descriptor ||
		in.velocity_descriptor != g_state.last_velocity_descriptor)
		copy_srvs(in.depth_descriptor, in.velocity_descriptor);

	// Fill this frame's slice of the constant ring.
	const UINT slot = g_state.frame % kFrameCount;
	g_state.frame++;

	Params params = {};
	std::memcpy(params.clip_to_prev_clip, in.view->clip_to_prev_clip.m, sizeof(params.clip_to_prev_clip));
	params.render_size[0] = static_cast<float>(in.render_width);
	params.render_size[1] = static_cast<float>(in.render_height);
	params.view_rect_min[0] = in.view->view_rect_min.x;
	params.view_rect_min[1] = in.view->view_rect_min.y;
	params.buffer_size[0] = in.view->buffer_size_and_inv_size.x;
	params.buffer_size[1] = in.view->buffer_size_and_inv_size.y;

	void *mapped = nullptr;
	D3D12_RANGE no_read = { 0, 0 };
	if (FAILED(g_state.constants->Map(0, &no_read, &mapped)) || mapped == nullptr)
		return false;
	std::memcpy(static_cast<uint8_t *>(mapped) + slot * g_state.constant_stride, &params, sizeof(params));
	D3D12_RANGE written = { slot * g_state.constant_stride,
	                        slot * g_state.constant_stride + sizeof(params) };
	g_state.constants->Unmap(0, &written);

	// The game's depth and velocity are in NON_PIXEL_SHADER_RESOURCE for its own TAA dispatch,
	// which is exactly what this pass needs too, so no transition is required for the inputs.
	cmd->SetComputeRootSignature(g_state.root_signature);
	cmd->SetPipelineState(g_state.pso);

	ID3D12DescriptorHeap *heaps[] = { g_state.heap };
	cmd->SetDescriptorHeaps(1, heaps);

	cmd->SetComputeRootConstantBufferView(0,
		g_state.constants->GetGPUVirtualAddress() + slot * g_state.constant_stride);
	cmd->SetComputeRootDescriptorTable(1, g_state.heap->GetGPUDescriptorHandleForHeapStart());

	if (dispatch_mode != 0)
	{
		const UINT gx = (dispatch_mode == 1) ? 1u : (g_state.width + 7) / 8;
		const UINT gy = (dispatch_mode == 1) ? 1u : (g_state.height + 7) / 8;
		cmd->Dispatch(gx, gy, 1);

		// The motion vectors are read by NGX immediately afterwards, so make the write visible.
		D3D12_RESOURCE_BARRIER uav_barrier = {};
		uav_barrier.Type = D3D12_RESOURCE_BARRIER_TYPE_UAV;
		uav_barrier.UAV.pResource = g_state.out_mv;
		cmd->ResourceBarrier(1, &uav_barrier);
	}

	return true;
}

} // namespace stray_dlss::mv
