#include "mv_resolve.hpp"

#include "core/ring.hpp"
#include "core/view_params.hpp"
#include "log.hpp"

#include <d3d12.h>

#include <mv_resolve.h> // g_mv_resolve_dxbc, generated by fxc at build time

#include <cstdio>
#include <cstring>
#include <algorithm>
#include <mutex>
#include <vector>

namespace stray_dlss::mv {
namespace {

// Matches the cbuffer in shaders/mv_resolve.hlsl. Kept in the same order deliberately; a
// mismatch here produces a plausible-looking but wrong motion field rather than an error.
struct Params
{
	float clip_to_prev_clip[16];
	float render_size[2];
	float view_rect_min[2];
	float buffer_size[2];
	float padding[2];
};
static_assert(sizeof(Params) % 16 == 0, "constant buffer must be 16-byte aligned");

// The versioning arithmetic lives in core/ring.hpp so it can be unit-tested; getting a slot
// offset wrong corrupts silently rather than failing.
constexpr UINT kDescriptorsPerFrame = ring::kDescriptorsPerFrame;
constexpr UINT kFrameCount = ring::kFrameCount;
constexpr UINT kDescriptorCount = ring::kDescriptorCount;

struct State
{
	ID3D12Device *device = nullptr;

	ID3D12RootSignature *root_signature = nullptr;
	ID3D12PipelineState *pso = nullptr;
	ID3D12DescriptorHeap *heap = nullptr;      // shader-visible CBV/SRV/UAV
	// ClearUnorderedAccessViewFloat needs the SAME descriptor twice: a GPU handle in a
	// shader-visible heap currently bound on the command list, and a CPU handle in a
	// NON-shader-visible heap. These two tiny heaps (one slot per ring frame) exist only for
	// the paint diagnostic.
	ID3D12DescriptorHeap *paint_heap = nullptr;     // shader-visible
	ID3D12DescriptorHeap *paint_staging = nullptr;  // CPU-only
	std::uint64_t paint_frame = 0;
	ID3D12Resource *constants = nullptr;       // upload heap, kFrameCount * aligned Params
	ID3D12Resource *out_mv = nullptr;          // R16G16_FLOAT at render resolution

	UINT descriptor_size = 0;
	UINT constant_stride = 0;
	std::uint64_t frame = 0;

	// The size actually ALLOCATED, which only ever grows. The size in use each frame can be
	// smaller; the shader bounds itself by RenderSize from the constant buffer.
	std::uint32_t width = 0;
	std::uint32_t height = 0;

	// Deliberately NO descriptor cache keyed on handle VALUES. UE4's offline descriptor
	// allocator recycles freed slots, so a destroyed velocity buffer's SRV and its replacement
	// land on the SAME CPU handle. Comparing handles then skips the copy and leaves our heap
	// pointing at a view of a resource vkd3d-proton has already destroyed — the GPU reads freed
	// memory, which is the crash. The copy is cheap; do it every frame.

	// Resources retired by a resolution change, released only once the GPU can no longer be
	// referencing them. Releasing immediately frees a descriptor heap that in-flight command
	// lists still bind.
	struct Retired
	{
		ID3D12DescriptorHeap *heap = nullptr;
		ID3D12Resource *constants = nullptr;
		ID3D12Resource *out_mv = nullptr;
		std::uint64_t retire_frame = 0;
	};
	std::vector<Retired> retired;

	Stats stats;

	char error[256] = {};
};

State g_state;

void set_error(const char *what, HRESULT hr)
{
	std::snprintf(g_state.error, sizeof(g_state.error), "%s (hr=0x%08x)", what,
		static_cast<unsigned int>(hr));
	STRAY_LOG_ERROR("mv_resolve: %s", g_state.error);
}

template <typename T>
void release(T *&p)
{
	if (p != nullptr)
	{
		p->Release();
		p = nullptr;
	}
}

bool create_root_signature()
{
	D3D12_DESCRIPTOR_RANGE ranges[2] = {};
	ranges[0].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
	ranges[0].NumDescriptors = 2; // t0 depth, t1 velocity
	ranges[0].BaseShaderRegister = 0;
	ranges[0].OffsetInDescriptorsFromTableStart = 0;
	ranges[1].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
	ranges[1].NumDescriptors = 1; // u0 output
	ranges[1].BaseShaderRegister = 0;
	ranges[1].OffsetInDescriptorsFromTableStart = 2;

	D3D12_ROOT_PARAMETER params[2] = {};
	params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_CBV;
	params[0].Descriptor.ShaderRegister = 0; // b0
	params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
	params[1].DescriptorTable.NumDescriptorRanges = 2;
	params[1].DescriptorTable.pDescriptorRanges = ranges;

	D3D12_ROOT_SIGNATURE_DESC desc = {};
	desc.NumParameters = 2;
	desc.pParameters = params;
	desc.Flags = D3D12_ROOT_SIGNATURE_FLAG_NONE;

	ID3DBlob *blob = nullptr;
	ID3DBlob *errors = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(&desc, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &errors);
	if (FAILED(hr))
	{
		if (errors != nullptr)
		{
			STRAY_LOG_ERROR("mv_resolve: root signature: %.*s",
				static_cast<int>(errors->GetBufferSize()),
				static_cast<const char *>(errors->GetBufferPointer()));
			errors->Release();
		}
		set_error("D3D12SerializeRootSignature", hr);
		return false;
	}
	if (errors != nullptr)
		errors->Release();

	hr = g_state.device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(),
		IID_PPV_ARGS(&g_state.root_signature));
	blob->Release();

	if (FAILED(hr))
	{
		set_error("CreateRootSignature", hr);
		return false;
	}
	return true;
}

bool create_pipeline()
{
	D3D12_COMPUTE_PIPELINE_STATE_DESC desc = {};
	desc.pRootSignature = g_state.root_signature;
	desc.CS.pShaderBytecode = g_mv_resolve_dxbc;
	desc.CS.BytecodeLength = sizeof(g_mv_resolve_dxbc);

	const HRESULT hr = g_state.device->CreateComputePipelineState(&desc, IID_PPV_ARGS(&g_state.pso));
	if (FAILED(hr))
	{
		set_error("CreateComputePipelineState", hr);
		return false;
	}
	return true;
}

bool create_resources(std::uint32_t width, std::uint32_t height)
{
	// Our own shader-visible heap. NGX will clobber whatever heap is bound when it runs, so
	// there is no way to share the game's, and no benefit in trying.
	D3D12_DESCRIPTOR_HEAP_DESC heap_desc = {};
	heap_desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
	heap_desc.NumDescriptors = kDescriptorCount;
	heap_desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;

	HRESULT hr = g_state.device->CreateDescriptorHeap(&heap_desc, IID_PPV_ARGS(&g_state.heap));
	if (FAILED(hr))
	{
		set_error("CreateDescriptorHeap", hr);
		return false;
	}

	g_state.descriptor_size =
		g_state.device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

	{
		D3D12_DESCRIPTOR_HEAP_DESC paint_desc = {};
		paint_desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
		paint_desc.NumDescriptors = ring::kFrameCount;
		paint_desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
		hr = g_state.device->CreateDescriptorHeap(&paint_desc, IID_PPV_ARGS(&g_state.paint_heap));
		if (FAILED(hr))
		{
			set_error("CreateDescriptorHeap(paint_heap)", hr);
			return false;
		}
		paint_desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_NONE;
		hr = g_state.device->CreateDescriptorHeap(&paint_desc, IID_PPV_ARGS(&g_state.paint_staging));
		if (FAILED(hr))
		{
			set_error("CreateDescriptorHeap(paint_staging)", hr);
			return false;
		}
	}

	// Constant buffer offsets must be 256-byte aligned.
	g_state.constant_stride = ring::aligned_constant_stride(sizeof(Params));

	D3D12_HEAP_PROPERTIES upload = {};
	upload.Type = D3D12_HEAP_TYPE_UPLOAD;

	D3D12_RESOURCE_DESC buf = {};
	buf.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
	buf.Width = static_cast<UINT64>(g_state.constant_stride) * kFrameCount;
	buf.Height = 1;
	buf.DepthOrArraySize = 1;
	buf.MipLevels = 1;
	buf.Format = DXGI_FORMAT_UNKNOWN;
	buf.SampleDesc.Count = 1;
	buf.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;

	hr = g_state.device->CreateCommittedResource(&upload, D3D12_HEAP_FLAG_NONE, &buf,
		D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(&g_state.constants));
	if (FAILED(hr))
	{
		set_error("CreateCommittedResource(constants)", hr);
		return false;
	}

	D3D12_HEAP_PROPERTIES default_heap = {};
	default_heap.Type = D3D12_HEAP_TYPE_DEFAULT;

	D3D12_RESOURCE_DESC tex = {};
	tex.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
	tex.Width = width;
	tex.Height = height;
	tex.DepthOrArraySize = 1;
	tex.MipLevels = 1;
	// The only motion-vector formats DLSS accepts are RG16_FLOAT and RG32_FLOAT.
	// (docs/RESEARCH.md §3.2)
	tex.Format = DXGI_FORMAT_R16G16_FLOAT;
	tex.SampleDesc.Count = 1;
	tex.Layout = D3D12_TEXTURE_LAYOUT_UNKNOWN;
	// ALLOW_UNORDERED_ACCESS is not optional: without it NGX can return success and write
	// nothing, which shows up as a black image with no error at all. (docs/RESEARCH.md §3.5)
	tex.Flags = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;

	hr = g_state.device->CreateCommittedResource(&default_heap, D3D12_HEAP_FLAG_NONE, &tex,
		D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, IID_PPV_ARGS(&g_state.out_mv));
	if (FAILED(hr))
	{
		set_error("CreateCommittedResource(out_mv)", hr);
		return false;
	}

	// The UAV never changes, but each frame's slice needs its own copy of it.
	D3D12_CPU_DESCRIPTOR_HANDLE base = g_state.heap->GetCPUDescriptorHandleForHeapStart();
	D3D12_UNORDERED_ACCESS_VIEW_DESC uav_desc = {};
	uav_desc.Format = DXGI_FORMAT_R16G16_FLOAT;
	uav_desc.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;

	for (UINT f = 0; f < kFrameCount; ++f)
	{
		D3D12_CPU_DESCRIPTOR_HANDLE uav = base;
		uav.ptr += ring::descriptor_offset_in_slot(f, 2, g_state.descriptor_size);
		g_state.device->CreateUnorderedAccessView(g_state.out_mv, nullptr, &uav_desc, uav);
	}

	g_state.width = width;
	g_state.height = height;
	++g_state.stats.resource_sets_created;
	return true;
}

// Copies the game's own SRV descriptors into our heap.
//
// This deliberately does NOT recreate the views from resource pointers. ReShade never calls
// destroy_resource_view on D3D12, so its view->resource map can return a pointer to a resource
// the game already destroyed; passing that to CreateShaderResourceView is an access violation,
// and the game rotates its velocity buffer constantly, so it happens within seconds. Copying
// descriptors needs no resource pointer and no format guessing — the game already described
// the view exactly as its own shader reads it. (docs/RESEARCH.md §2.7)
// The SRV format to view a resource through.
//
// Depth is created TYPELESS so it can carry both depth and stencil, and a view must name one
// plane explicitly — the depth plane here. Getting this wrong is not survivable: the debug
// layer rejects the view and REMOVES THE DEVICE (seen in our own CI when R32_FLOAT was used
// for an R32G8X24_TYPELESS resource).
DXGI_FORMAT srv_format_for(DXGI_FORMAT resource_format)
{
	switch (resource_format)
	{
	case DXGI_FORMAT_R32G8X24_TYPELESS:     return DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS;
	case DXGI_FORMAT_R24G8_TYPELESS:        return DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
	case DXGI_FORMAT_R32_TYPELESS:          return DXGI_FORMAT_R32_FLOAT;
	case DXGI_FORMAT_R16_TYPELESS:          return DXGI_FORMAT_R16_UNORM;
	case DXGI_FORMAT_R16G16B16A16_TYPELESS: return DXGI_FORMAT_R16G16B16A16_UNORM;
	default:                                return resource_format;  // already typed
	}
}

// Builds THIS frame's SRVs for the game's depth and velocity, straight into our own heap.
//
// We do NOT copy the game's descriptors. Measured in the live game, they live in the heap UE4
// has bound — type=0, 500000 descriptors, SHADER_VISIBLE=YES — and D3D12 forbids a
// shader-visible copy source (#654, reproduced in CI). vkd3d-proton raises nothing, so the
// illegal copy quietly produced a descriptor the GPU rejected on first read: Xid 109.
void create_srvs(UINT slot, ID3D12Resource *depth, ID3D12Resource *velocity)
{
	D3D12_CPU_DESCRIPTOR_HANDLE dest = g_state.heap->GetCPUDescriptorHandleForHeapStart();
	dest.ptr += ring::descriptor_offset(slot, g_state.descriptor_size);

	D3D12_SHADER_RESOURCE_VIEW_DESC srv = {};
	srv.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
	srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
	srv.Texture2D.MipLevels = 1;

	// Log every distinct resource once, immediately BEFORE viewing it.
	//
	// Under vkd3d a bad view faults inside the driver — "err:vulkan:vkCreateImageView Exception
	// 0xc0000005" — with nothing to say which resource or which field was wrong. Printing the
	// desc first localises it: if the log line is missing, GetDesc itself faulted and the
	// pointer is stale; if it is present, the pointer was live and the view description is at
	// fault.
	const auto note = [](const char *what, ID3D12Resource *res) {
		static std::mutex m;
		static std::vector<ID3D12Resource *> seen;
		{
			std::lock_guard<std::mutex> lock(m);
			if (std::find(seen.begin(), seen.end(), res) != seen.end())
				return;
			seen.push_back(res);
		}
		const D3D12_RESOURCE_DESC d = res->GetDesc();
		STRAY_LOG_INFO("about to view %s %p: dim=%d fmt=%d %llux%u mips=%u arr=%u samples=%u "
			"flags=0x%x", what, static_cast<void *>(res), static_cast<int>(d.Dimension),
			static_cast<int>(d.Format), static_cast<unsigned long long>(d.Width), d.Height,
			d.MipLevels, d.DepthOrArraySize, d.SampleDesc.Count,
			static_cast<unsigned>(d.Flags));
	};

	note("depth", depth);
	const D3D12_RESOURCE_DESC dd = depth->GetDesc();
	srv.Format = srv_format_for(dd.Format);
	// A multisampled resource needs a TEXTURE2DMS view; asking for TEXTURE2D builds a Vulkan
	// image view the driver rejects.
	srv.ViewDimension = dd.SampleDesc.Count > 1 ? D3D12_SRV_DIMENSION_TEXTURE2DMS
	                                            : D3D12_SRV_DIMENSION_TEXTURE2D;
	g_state.device->CreateShaderResourceView(depth, &srv, dest);

	dest.ptr += g_state.descriptor_size;
	note("velocity", velocity);
	const D3D12_RESOURCE_DESC vd = velocity->GetDesc();
	srv.Format = srv_format_for(vd.Format);
	srv.ViewDimension = vd.SampleDesc.Count > 1 ? D3D12_SRV_DIMENSION_TEXTURE2DMS
	                                            : D3D12_SRV_DIMENSION_TEXTURE2D;
	srv.Texture2D.MipLevels = 1;
	g_state.device->CreateShaderResourceView(velocity, &srv, dest);
}

// Releases retired resources once kFrameCount further frames have been recorded, by which point
// no in-flight list can still reference them.
void retire_expired()
{
	for (auto it = g_state.retired.begin(); it != g_state.retired.end();)
	{
		if (!ring::is_safe_to_release(g_state.frame, it->retire_frame))
		{
			++it;
			continue;
		}
		release(it->heap);
		release(it->constants);
		release(it->out_mv);
		it = g_state.retired.erase(it);
		++g_state.stats.resource_sets_released;
		g_state.stats.live_retired = static_cast<std::uint32_t>(g_state.retired.size());
	}
}

} // namespace

const char *last_error() { return g_state.error; }

const Stats &stats()
{
	// Recomputed on read so it stays honest even if a release path is added later.
	g_state.stats.live_retired = static_cast<std::uint32_t>(g_state.retired.size());
	std::uint64_t bytes = 0;
	if (g_state.out_mv != nullptr)
		bytes += static_cast<std::uint64_t>(g_state.width) * g_state.height * 4;
	for (const auto &r : g_state.retired)
		if (r.out_mv != nullptr)
			bytes += static_cast<std::uint64_t>(g_state.width) * g_state.height * 4;
	g_state.stats.bytes_live = bytes;
	return g_state.stats;
}
bool is_ready() { return g_state.pso != nullptr && g_state.out_mv != nullptr; }
ID3D12Resource *output() { return g_state.out_mv; }

bool initialise(ID3D12Device *device, std::uint32_t width, std::uint32_t height)
{
	if (device == nullptr || width == 0 || height == 0)
		return false;

	// GROW-ONLY. Reallocating whenever the resolution changes is what killed the machine: the
	// render resolution comes from whichever dispatch matched, so it alternates during loading,
	// and each change orphaned a descriptor heap, constant buffer and output texture. Freeing
	// those on a frame counter has nothing to do with when the GPU finished with them — the
	// WARP harness reproduces it in 200 frames as "resource deleted prior to closing the
	// command list", followed by DEVICE_REMOVED. On the real machine it read as
	// NV_ERR_NO_MEMORY, then Xid 109 CTX SWITCH TIMEOUT, then a hang.
	//
	// Allocating for the largest size seen removes the churn entirely rather than trying to
	// time the frees correctly. A smaller frame simply dispatches over part of the texture.
	if (g_state.device != device)
	{
		shutdown();
		g_state.device = device;
	}

	const bool fits = width <= g_state.width && height <= g_state.height;
	if (fits && is_ready())
		return true;

	if (!fits && is_ready())
	{
		// Growing. Rare — at most a couple of times per session — so the old set is simply kept
		// alive until shutdown rather than freed on a guess about GPU progress.
		State::Retired r;
		r.heap = g_state.heap;
		r.constants = g_state.constants;
		r.out_mv = g_state.out_mv;
		r.retire_frame = g_state.frame;
		g_state.retired.push_back(r);
		++g_state.stats.resource_sets_retired;
		g_state.stats.live_retired = static_cast<std::uint32_t>(g_state.retired.size());

		g_state.heap = nullptr;
		g_state.constants = nullptr;
		g_state.out_mv = nullptr;

		width = width > g_state.width ? width : g_state.width;
		height = height > g_state.height ? height : g_state.height;
	}

	if (g_state.root_signature == nullptr && !create_root_signature())
		return false;
	if (g_state.pso == nullptr && !create_pipeline())
		return false;
	if (g_state.heap == nullptr && !create_resources(width, height))
		return false;

	STRAY_LOG_INFO("mv_resolve ready: R16G16_FLOAT %ux%u", width, height);
	return true;
}

void shutdown()
{
	for (auto &r : g_state.retired)
	{
		release(r.heap);
		release(r.constants);
		release(r.out_mv);
	}
	g_state.retired.clear();

	release(g_state.out_mv);
	release(g_state.constants);
	release(g_state.heap);
	release(g_state.paint_heap);
	release(g_state.paint_staging);
	release(g_state.pso);
	release(g_state.root_signature);
	g_state.device = nullptr;
	g_state.width = 0;
	g_state.height = 0;

}

void transition_output(ID3D12GraphicsCommandList *cmd, bool to_shader_resource)
{
	if (cmd == nullptr || g_state.out_mv == nullptr)
		return;

	D3D12_RESOURCE_BARRIER barrier = {};
	barrier.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
	barrier.Transition.pResource = g_state.out_mv;
	barrier.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
	barrier.Transition.StateBefore = to_shader_resource
		? D3D12_RESOURCE_STATE_UNORDERED_ACCESS
		: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
	barrier.Transition.StateAfter = to_shader_resource
		? D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE
		: D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
	cmd->ResourceBarrier(1, &barrier);
}

bool paint(ID3D12GraphicsCommandList *cmd, ID3D12Resource *target)
{
	if (cmd == nullptr || target == nullptr || !is_ready() ||
		g_state.paint_heap == nullptr || g_state.paint_staging == nullptr)
		return false;

	// One descriptor per ring slot so an in-flight frame's descriptor is never rewritten.
	const UINT slot = ring::slot_for_frame(g_state.paint_frame++);
	const SIZE_T off = static_cast<SIZE_T>(slot) * g_state.descriptor_size;
	D3D12_CPU_DESCRIPTOR_HANDLE cpu_vis = g_state.paint_heap->GetCPUDescriptorHandleForHeapStart();
	cpu_vis.ptr += off;
	D3D12_GPU_DESCRIPTOR_HANDLE gpu_vis = g_state.paint_heap->GetGPUDescriptorHandleForHeapStart();
	gpu_vis.ptr += off;
	D3D12_CPU_DESCRIPTOR_HANDLE cpu_stage =
		g_state.paint_staging->GetCPUDescriptorHandleForHeapStart();
	cpu_stage.ptr += off;

	D3D12_UNORDERED_ACCESS_VIEW_DESC uav = {};
	uav.Format = target->GetDesc().Format;
	uav.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
	g_state.device->CreateUnorderedAccessView(target, nullptr, &uav, cpu_vis);
	g_state.device->CreateUnorderedAccessView(target, nullptr, &uav, cpu_stage);

	ID3D12DescriptorHeap *heaps[] = { g_state.paint_heap };
	cmd->SetDescriptorHeaps(1, heaps);

	// Magenta: unmistakable, and never produced by the game. The output is expected in
	// UNORDERED_ACCESS here — the engine transitioned it for the dispatch we are replacing.
	const float magenta[4] = { 1.0f, 0.0f, 1.0f, 1.0f };
	cmd->ClearUnorderedAccessViewFloat(gpu_vis, cpu_stage, target, magenta, 0, nullptr);
	return true;
}

bool record(ID3D12GraphicsCommandList *cmd, const ResolveInputs &in, int dispatch_mode)
{
	if (cmd == nullptr || !is_ready() || in.depth_resource == 0 ||
		in.velocity_resource == 0 || in.view == nullptr)
		return false;

	// This frame's slice of every per-frame resource.
	const UINT slot = ring::slot_for_frame(g_state.frame);
	g_state.frame++;

	// Unconditionally, every frame. See the note on the removed descriptor cache.
	create_srvs(slot, reinterpret_cast<ID3D12Resource *>(in.depth_resource),
		reinterpret_cast<ID3D12Resource *>(in.velocity_resource));

	retire_expired();

	Params params = {};
	std::memcpy(params.clip_to_prev_clip, in.view->clip_to_prev_clip.m, sizeof(params.clip_to_prev_clip));
	params.render_size[0] = static_cast<float>(in.render_width);
	params.render_size[1] = static_cast<float>(in.render_height);
	params.view_rect_min[0] = in.view->view_rect_min.x;
	params.view_rect_min[1] = in.view->view_rect_min.y;
	params.buffer_size[0] = in.view->buffer_size_and_inv_size.x;
	params.buffer_size[1] = in.view->buffer_size_and_inv_size.y;

	void *mapped = nullptr;
	D3D12_RANGE no_read = { 0, 0 };
	if (FAILED(g_state.constants->Map(0, &no_read, &mapped)) || mapped == nullptr)
		return false;
	const std::size_t cb_offset = ring::constant_offset(slot, g_state.constant_stride);
	std::memcpy(static_cast<uint8_t *>(mapped) + cb_offset, &params, sizeof(params));
	D3D12_RANGE written = { cb_offset, cb_offset + sizeof(params) };
	g_state.constants->Unmap(0, &written);

	// The game's depth and velocity are in NON_PIXEL_SHADER_RESOURCE for its own TAA dispatch,
	// which is exactly what this pass needs too, so no transition is required for the inputs.
	cmd->SetComputeRootSignature(g_state.root_signature);
	cmd->SetPipelineState(g_state.pso);

	ID3D12DescriptorHeap *heaps[] = { g_state.heap };
	cmd->SetDescriptorHeaps(1, heaps);

	cmd->SetComputeRootConstantBufferView(0,
		g_state.constants->GetGPUVirtualAddress() + cb_offset);
	D3D12_GPU_DESCRIPTOR_HANDLE table = g_state.heap->GetGPUDescriptorHandleForHeapStart();
	table.ptr += ring::descriptor_offset(slot, g_state.descriptor_size);
	cmd->SetComputeRootDescriptorTable(1, table);

	if (dispatch_mode != 0)
	{
		// Over the FRAME's size, not the allocated size — the texture may be larger under the
		// grow-only policy, and the shader bounds itself by RenderSize anyway.
		const UINT gx = (dispatch_mode == 1) ? 1u : (in.render_width + 7) / 8;
		const UINT gy = (dispatch_mode == 1) ? 1u : (in.render_height + 7) / 8;
		cmd->Dispatch(gx, gy, 1);

		// The motion vectors are read by NGX immediately afterwards, so make the write visible.
		D3D12_RESOURCE_BARRIER uav_barrier = {};
		uav_barrier.Type = D3D12_RESOURCE_BARRIER_TYPE_UAV;
		uav_barrier.UAV.pResource = g_state.out_mv;
		cmd->ResourceBarrier(1, &uav_barrier);
	}

	return true;
}

} // namespace stray_dlss::mv
