#include "nr_codec_pass.hpp"

#include "core/nr_lifetime.hpp"
#include "core/ring.hpp"
#include "log.hpp"

#include <d3d12.h>

#include <nr_decode.h> // g_nr_decode_dxbc, generated by fxc at build time
#include <nr_encode.h> // g_nr_encode_dxbc

#include <cstdio>
#include <cstring>
#include <vector>

namespace stray_dlss::nrp {
namespace {

// Matches `cbuffer NrCodecParams` in shaders/nr_codec.hlsli. Same order deliberately; a
// mismatch produces a plausible-looking but wrong image rather than an error. (gbuffer_resolve
// precedent.)
struct Params
{
	std::uint32_t image_size[2];
	float scale;
	float color_strength;
	float transfer_strength;
	float pad0;
	float pad1;
	float pad2;
};
static_assert(sizeof(Params) % 16 == 0, "constant buffer must be 16-byte aligned");

// Both dispatches share one root signature and one table shape: three UAVs at u0..u2.
//   encode: u0 = engine image (read), u1 = proxy (written), u2 unused
//   decode: u0 = proxy,               u1 = neural,          u2 = engine image (read+written)
// The root signature is allowed to declare more than a shader uses, so one shape covers both.
constexpr UINT kUavCount = 3;
// Six per frame slice: the encode's three, then the decode's three. The two dispatches run in
// the SAME frame, so they cannot share one set of descriptor slots.
constexpr UINT kDescriptorsPerFrame = kUavCount * 2;
constexpr UINT kEncodeBase = 0;
constexpr UINT kDecodeBase = kUavCount;
constexpr UINT kFrameCount = ring::kFrameCount;
constexpr UINT kDescriptorCount = kDescriptorsPerFrame * kFrameCount;

// The proxy is ALWAYS FP16 RGBA, whatever the engine image happens to be. The reference
// deployment is explicit about this ("soft-clips and sRGB-encodes into an FP16 proxy"), and it
// matters: the proxy carries an sRGB-encoded [0,1] signal, and R11G11B10_FLOAT — which this
// title's colour target genuinely is in the main menu (CLAUDE.md §5) — has a 6-bit mantissa,
// i.e. less precision there than plain 8-bit sRGB. The decode subtracts two of these, so
// proxy precision is directly the noise floor of the whole transfer.
constexpr DXGI_FORMAT kProxyFormat = DXGI_FORMAT_R16G16B16A16_FLOAT;
constexpr std::uint64_t kProxyBytesPerPixel = 8;

struct State
{
	ID3D12Device *device = nullptr;

	ID3D12RootSignature *root_signature = nullptr;
	ID3D12PipelineState *encode_pso = nullptr;
	ID3D12PipelineState *decode_pso = nullptr;
	ID3D12DescriptorHeap *heap = nullptr; // shader-visible CBV/SRV/UAV
	ID3D12Resource *constants = nullptr;  // upload heap, kFrameCount * aligned Params
	ID3D12Resource *proxy = nullptr;

	UINT descriptor_size = 0;
	UINT constant_stride = 0;
	std::uint64_t frame = 0;

	// Allocated size — grow-only; both dispatches bound themselves by the frame's own rect.
	std::uint32_t width = 0;
	std::uint32_t height = 0;

	// The engine image's format, validated once for typed UAV load/store. The neural output
	// shares it (ngx_nr allocates that texture from the image's own desc), so one check covers
	// every UAV we create over someone else's resource.
	DXGI_FORMAT image_format = DXGI_FORMAT_UNKNOWN;
	bool format_checked = false;

	// The ring slot record_encode claimed this frame, and whether it claimed one at all. The
	// decode must land in the same slot: it reads the constants the encode wrote and the
	// descriptors it built.
	UINT current_slot = 0;
	bool encoded_this_frame = false;

	// The GPU timeline every deferred free below is decided against. ngx_nr owns the fence and
	// pushes this down each frame; until it does, `have_fence` is false and the conservative
	// present ring decides instead (core/nr_lifetime.hpp).
	nrlife::Timeline timeline;

	// Everything this pass owns, waiting out the GPU. The PSOs and the root signature are in here
	// as well as the textures and the heap: a command list still in flight references all of
	// them, and D3D12 does not keep a PSO alive for a recorded-but-unexecuted list.
	struct Retired
	{
		ID3D12DescriptorHeap *heap = nullptr;
		ID3D12Resource *constants = nullptr;
		ID3D12Resource *proxy = nullptr;
		ID3D12PipelineState *encode_pso = nullptr;
		ID3D12PipelineState *decode_pso = nullptr;
		ID3D12RootSignature *root_signature = nullptr;
		nrlife::Tag tag;
		std::uint64_t bytes = 0;
	};
	std::vector<Retired> retired;

	// Resources AddRef'd at record time and released only once the GPU can no longer be reading
	// them — the mv_resolve keep-alive, for the same measured Xid-109 reason. The engine image
	// and the neural texture are both owned elsewhere.
	struct LiveInput
	{
		ID3D12Resource *a = nullptr;
		ID3D12Resource *b = nullptr;
		nrlife::Tag tag;
	};
	std::vector<LiveInput> input_keep_alive;

	Stats stats;
	char error[256] = {};
};

State g_state;

void set_error(const char *what, HRESULT hr)
{
	std::snprintf(g_state.error, sizeof(g_state.error), "%s (hr=0x%08x)", what,
		static_cast<unsigned int>(hr));
	STRAY_LOG_ERROR("nr_codec: %s", g_state.error);
}

void set_error_text(const char *what)
{
	std::snprintf(g_state.error, sizeof(g_state.error), "%s", what);
	STRAY_LOG_ERROR("nr_codec: %s", g_state.error);
}

template <typename T>
void release(T *&p)
{
	if (p != nullptr)
	{
		p->Release();
		p = nullptr;
	}
}

bool create_root_signature()
{
	D3D12_DESCRIPTOR_RANGE range = {};
	range.RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
	range.NumDescriptors = kUavCount; // u0..u2
	range.BaseShaderRegister = 0;
	range.OffsetInDescriptorsFromTableStart = 0;

	D3D12_ROOT_PARAMETER params[2] = {};
	params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_CBV;
	params[0].Descriptor.ShaderRegister = 0; // b0
	params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
	params[1].DescriptorTable.NumDescriptorRanges = 1;
	params[1].DescriptorTable.pDescriptorRanges = &range;

	D3D12_ROOT_SIGNATURE_DESC desc = {};
	desc.NumParameters = 2;
	desc.pParameters = params;
	desc.Flags = D3D12_ROOT_SIGNATURE_FLAG_NONE;

	ID3DBlob *blob = nullptr;
	ID3DBlob *errors = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(&desc, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &errors);
	if (FAILED(hr))
	{
		if (errors != nullptr)
		{
			STRAY_LOG_ERROR("nr_codec: root signature: %.*s",
				static_cast<int>(errors->GetBufferSize()),
				static_cast<const char *>(errors->GetBufferPointer()));
			errors->Release();
		}
		set_error("D3D12SerializeRootSignature", hr);
		return false;
	}
	if (errors != nullptr)
		errors->Release();

	hr = g_state.device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(),
		IID_PPV_ARGS(&g_state.root_signature));
	blob->Release();

	if (FAILED(hr))
	{
		set_error("CreateRootSignature", hr);
		return false;
	}
	return true;
}

bool create_pipeline(const void *dxbc, std::size_t size, const char *what,
                     ID3D12PipelineState **out)
{
	D3D12_COMPUTE_PIPELINE_STATE_DESC desc = {};
	desc.pRootSignature = g_state.root_signature;
	desc.CS.pShaderBytecode = dxbc;
	desc.CS.BytecodeLength = size;

	const HRESULT hr = g_state.device->CreateComputePipelineState(&desc, IID_PPV_ARGS(out));
	if (FAILED(hr))
	{
		set_error(what, hr);
		return false;
	}
	return true;
}

// A format the device cannot load AND store through a typed UAV would make both dispatches
// silently no-op — the exact "black output with no further indication" failure class
// (CLAUDE.md §0.2). Ask the device instead of assuming.
//
// Implemented on top of the public probe so there is exactly ONE CheckFeatureSupport call site
// for typed UAVs in this codebase; the post-tonemap NR hook reuses the same probe on the back
// buffer and needs the individual bits, which this predicate collapses.
bool format_supports_typed_uav(DXGI_FORMAT format)
{
	const TypedUavSupport s = probe_typed_uav(g_state.device, static_cast<int>(format));
	return s.queried && s.view && s.load && s.store;
}

bool create_resources(std::uint32_t width, std::uint32_t height)
{
	// Our own shader-visible heap; NGX clobbers whatever heap is bound when it runs.
	D3D12_DESCRIPTOR_HEAP_DESC heap_desc = {};
	heap_desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
	heap_desc.NumDescriptors = kDescriptorCount;
	heap_desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;

	HRESULT hr = g_state.device->CreateDescriptorHeap(&heap_desc, IID_PPV_ARGS(&g_state.heap));
	if (FAILED(hr))
	{
		set_error("CreateDescriptorHeap", hr);
		return false;
	}

	g_state.descriptor_size =
		g_state.device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
	g_state.constant_stride = ring::aligned_constant_stride(sizeof(Params));

	D3D12_HEAP_PROPERTIES upload = {};
	upload.Type = D3D12_HEAP_TYPE_UPLOAD;

	D3D12_RESOURCE_DESC buf = {};
	buf.Dimension = D3D12_RESOURCE_DIMENSION_BUFFER;
	buf.Width = static_cast<UINT64>(g_state.constant_stride) * kFrameCount;
	buf.Height = 1;
	buf.DepthOrArraySize = 1;
	buf.MipLevels = 1;
	buf.Format = DXGI_FORMAT_UNKNOWN;
	buf.SampleDesc.Count = 1;
	buf.Layout = D3D12_TEXTURE_LAYOUT_ROW_MAJOR;

	hr = g_state.device->CreateCommittedResource(&upload, D3D12_HEAP_FLAG_NONE, &buf,
		D3D12_RESOURCE_STATE_GENERIC_READ, nullptr, IID_PPV_ARGS(&g_state.constants));
	if (FAILED(hr))
	{
		set_error("CreateCommittedResource(constants)", hr);
		return false;
	}

	D3D12_HEAP_PROPERTIES default_heap = {};
	default_heap.Type = D3D12_HEAP_TYPE_DEFAULT;

	// PLAIN, TYPED, SINGLE-SUBRESOURCE. Never mirror whatever UE4 allocated: a mipped texture
	// handed to this neural runtime is a documented DXGI_ERROR_DEVICE_HUNG rather than an error
	// return (the same lesson ngx_nr::ensure_output_texture carries), and this texture IS an
	// NGX input — it is what DLSSNR.Color points at.
	D3D12_RESOURCE_DESC tex = {};
	tex.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
	tex.Width = width;
	tex.Height = height;
	tex.DepthOrArraySize = 1;
	tex.MipLevels = 1;
	tex.Format = kProxyFormat;
	tex.SampleDesc.Count = 1;
	tex.SampleDesc.Quality = 0;
	tex.Layout = D3D12_TEXTURE_LAYOUT_UNKNOWN;
	tex.Flags = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;

	hr = g_state.device->CreateCommittedResource(&default_heap, D3D12_HEAP_FLAG_NONE, &tex,
		D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, IID_PPV_ARGS(&g_state.proxy));
	if (FAILED(hr))
	{
		set_error("CreateCommittedResource(proxy)", hr);
		return false;
	}

	g_state.width = width;
	g_state.height = height;
	++g_state.stats.resource_sets_created;
	return true;
}

// Builds one UAV into this frame's slice. Unconditionally, every frame — never a cached handle
// and never a descriptor copy out of the game's heap (illegal as a copy source, D3D12 #654;
// and a recycled slot aliases a destroyed resource — CLAUDE.md §5).
void write_uav(UINT slot, UINT base, UINT index, ID3D12Resource *res, DXGI_FORMAT format)
{
	D3D12_UNORDERED_ACCESS_VIEW_DESC uav = {};
	uav.Format = format;
	uav.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;

	D3D12_CPU_DESCRIPTOR_HANDLE dest = g_state.heap->GetCPUDescriptorHandleForHeapStart();
	dest.ptr += ring::descriptor_offset_n(slot, kDescriptorsPerFrame, base + index,
		g_state.descriptor_size);
	g_state.device->CreateUnorderedAccessView(res, nullptr, &uav, dest);
}

// A null descriptor for the table slot a shader does not read. The table must be fully
// populated: the debug layer objects to a stale or uninitialised descriptor in a bound range
// even when nothing samples it.
void write_null_uav(UINT slot, UINT base, UINT index)
{
	D3D12_UNORDERED_ACCESS_VIEW_DESC uav = {};
	uav.Format = kProxyFormat;
	uav.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;

	D3D12_CPU_DESCRIPTOR_HANDLE dest = g_state.heap->GetCPUDescriptorHandleForHeapStart();
	dest.ptr += ring::descriptor_offset_n(slot, kDescriptorsPerFrame, base + index,
		g_state.descriptor_size);
	g_state.device->CreateUnorderedAccessView(nullptr, nullptr, &uav, dest);
}

void keep_alive(ID3D12Resource *a, ID3D12Resource *b)
{
	State::LiveInput li;
	li.a = a;
	li.b = b;
	li.tag = nrlife::tag_now(g_state.timeline);
	if (li.a != nullptr)
		li.a->AddRef();
	if (li.b != nullptr)
		li.b->AddRef();
	g_state.input_keep_alive.push_back(li);

	for (auto it = g_state.input_keep_alive.begin(); it != g_state.input_keep_alive.end();)
	{
		if (nrlife::safe_to_free(g_state.timeline, it->tag))
		{
			if (it->a != nullptr)
				it->a->Release();
			if (it->b != nullptr)
				it->b->Release();
			it = g_state.input_keep_alive.erase(it);
		}
		else
			++it;
	}
}

// Frees every retired set the GPU has demonstrably passed. NEVER frees on a timeline that has
// not moved — the whole point is that "we stopped using it" and "the GPU stopped reading it" are
// different moments.
void retire_expired()
{
	for (auto it = g_state.retired.begin(); it != g_state.retired.end();)
	{
		if (!nrlife::safe_to_free(g_state.timeline, it->tag))
		{
			++it;
			continue;
		}
		release(it->heap);
		release(it->constants);
		release(it->proxy);
		release(it->encode_pso);
		release(it->decode_pso);
		release(it->root_signature);
		it = g_state.retired.erase(it);
		++g_state.stats.resource_sets_released;
		g_state.stats.live_retired = static_cast<std::uint32_t>(g_state.retired.size());
	}
}

// Moves the whole live set into the graveyard, tagged against the current timeline. Callable from
// any thread: it destroys nothing.
void retire_live_set(bool include_pipelines)
{
	if (g_state.heap == nullptr && g_state.constants == nullptr && g_state.proxy == nullptr &&
		(!include_pipelines || (g_state.encode_pso == nullptr && g_state.decode_pso == nullptr &&
			g_state.root_signature == nullptr)))
		return;

	State::Retired r;
	r.heap = g_state.heap;
	r.constants = g_state.constants;
	r.proxy = g_state.proxy;
	r.tag = nrlife::tag_now(g_state.timeline);
	r.bytes = static_cast<std::uint64_t>(g_state.width) * g_state.height * kProxyBytesPerPixel;
	if (include_pipelines)
	{
		r.encode_pso = g_state.encode_pso;
		r.decode_pso = g_state.decode_pso;
		r.root_signature = g_state.root_signature;
		g_state.encode_pso = nullptr;
		g_state.decode_pso = nullptr;
		g_state.root_signature = nullptr;
	}
	g_state.retired.push_back(r);
	++g_state.stats.resource_sets_retired;
	g_state.stats.live_retired = static_cast<std::uint32_t>(g_state.retired.size());

	g_state.heap = nullptr;
	g_state.constants = nullptr;
	g_state.proxy = nullptr;
	g_state.encoded_this_frame = false;
}

// UAV barrier: make the previous writer's stores visible to the next reader on the same queue.
void uav_barrier(ID3D12GraphicsCommandList *cmd, ID3D12Resource *a, ID3D12Resource *b)
{
	D3D12_RESOURCE_BARRIER barriers[2] = {};
	UINT n = 0;
	if (a != nullptr)
	{
		barriers[n].Type = D3D12_RESOURCE_BARRIER_TYPE_UAV;
		barriers[n].UAV.pResource = a;
		++n;
	}
	if (b != nullptr)
	{
		barriers[n].Type = D3D12_RESOURCE_BARRIER_TYPE_UAV;
		barriers[n].UAV.pResource = b;
		++n;
	}
	if (n != 0)
		cmd->ResourceBarrier(n, barriers);
}

void bind_common(ID3D12GraphicsCommandList *cmd, UINT slot, UINT base, ID3D12PipelineState *pso)
{
	cmd->SetComputeRootSignature(g_state.root_signature);
	cmd->SetPipelineState(pso);

	ID3D12DescriptorHeap *heaps[] = { g_state.heap };
	cmd->SetDescriptorHeaps(1, heaps);

	cmd->SetComputeRootConstantBufferView(0, g_state.constants->GetGPUVirtualAddress() +
		ring::constant_offset(slot, g_state.constant_stride));

	D3D12_GPU_DESCRIPTOR_HANDLE table = g_state.heap->GetGPUDescriptorHandleForHeapStart();
	table.ptr += ring::descriptor_offset_n(slot, kDescriptorsPerFrame, base,
		g_state.descriptor_size);
	cmd->SetComputeRootDescriptorTable(1, table);
}

} // namespace

TypedUavSupport probe_typed_uav(ID3D12Device *device, int format)
{
	TypedUavSupport out;
	if (device == nullptr)
		return out;

	D3D12_FEATURE_DATA_FORMAT_SUPPORT support = {};
	support.Format = static_cast<DXGI_FORMAT>(format);
	if (FAILED(device->CheckFeatureSupport(D3D12_FEATURE_FORMAT_SUPPORT, &support,
			sizeof(support))))
		return out; // queried stays false: "the device would not answer", not "unsupported"

	out.queried = true;
	out.view = (support.Support1 & D3D12_FORMAT_SUPPORT1_TYPED_UNORDERED_ACCESS_VIEW) != 0;
	out.load = (static_cast<UINT>(support.Support2) & D3D12_FORMAT_SUPPORT2_UAV_TYPED_LOAD) != 0;
	out.store = (static_cast<UINT>(support.Support2) & D3D12_FORMAT_SUPPORT2_UAV_TYPED_STORE) != 0;
	return out;
}

const char *last_error() { return g_state.error; }

const Stats &stats()
{
	g_state.stats.live_retired = static_cast<std::uint32_t>(g_state.retired.size());
	std::uint64_t bytes = 0;
	if (g_state.proxy != nullptr)
		bytes += static_cast<std::uint64_t>(g_state.width) * g_state.height * kProxyBytesPerPixel;
	for (const auto &r : g_state.retired)
		bytes += r.bytes;
	g_state.stats.bytes_live = bytes;
	return g_state.stats;
}

bool is_ready()
{
	return g_state.encode_pso != nullptr && g_state.decode_pso != nullptr &&
		g_state.proxy != nullptr;
}

ID3D12Resource *proxy() { return g_state.proxy; }

bool initialise(ID3D12Device *device, ID3D12Resource *image, std::uint32_t width,
                std::uint32_t height)
{
	if (device == nullptr || image == nullptr || width == 0 || height == 0)
	{
		set_error_text("initialise: missing device, image or extent");
		return false;
	}

	if (g_state.device != device)
	{
		shutdown();
		g_state.device = device;
	}

	// The engine image's format has to survive a typed UAV load AND store: the encode reads
	// through one, the decode reads and writes through one. A TYPELESS resource cannot be
	// viewed without guessing a format, and guessing wrong here is a wrong image with no error.
	const D3D12_RESOURCE_DESC desc = image->GetDesc();

	// Both dispatches bind the engine image as a UAV, which requires the flag on the resource
	// itself. UE 4.27's TAA target carries it by construction (it is the `u0` the TAA pass
	// writes, CLAUDE.md §2.3), but assert it rather than assume: creating a UAV over a resource
	// without the flag is a debug-layer error on WARP and, under vkd3d-proton where no debug
	// layer exists, a garbage descriptor with no diagnostic at all.
	if ((desc.Flags & D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS) == 0)
	{
		std::snprintf(g_state.error, sizeof(g_state.error),
			"the engine colour image lacks ALLOW_UNORDERED_ACCESS (flags=0x%x)",
			static_cast<unsigned int>(desc.Flags));
		STRAY_LOG_ERROR("nr_codec: %s, so neither codec dispatch can bind it. This should be "
			"impossible for UE4's own TAA output; if it happens, the pass we hooked is not the "
			"one CLAUDE.md §2.3 describes. NR refuses rather than creating an invalid descriptor.",
			g_state.error);
		return false;
	}

	if (g_state.image_format != desc.Format)
	{
		g_state.image_format = desc.Format;
		g_state.format_checked = false;
	}
	if (!g_state.format_checked)
	{
		g_state.format_checked = true;
		if (!format_supports_typed_uav(desc.Format))
		{
			std::snprintf(g_state.error, sizeof(g_state.error),
				"the engine colour image's format (%d) does not support typed UAV load+store",
				static_cast<int>(desc.Format));
			STRAY_LOG_ERROR("nr_codec: %s, so the codec cannot read or write it. The HDR codec "
				"is REQUIRED for DLSS-NR (the network is display-referred and the runtime has no "
				"colour-space parameter), so NR refuses rather than running on raw HDR.",
				g_state.error);
			return false;
		}
	}

	// GROW-ONLY, exactly like mv_resolve and gbuffer_resolve, and for the measured reason:
	// reallocation churn during loading orphaned GPU-visible resources and OOM'd the machine.
	// A smaller frame dispatches over part of the texture.
	const bool fits = width <= g_state.width && height <= g_state.height;
	if (fits && is_ready())
		return true;

	if (!fits && is_ready())
	{
		// The PSOs and the root signature do not depend on the extent, so they are kept live
		// across a grow rather than rebuilt — but the heap, the constants and the proxy are
		// retired against the GPU timeline, never freed here.
		retire_live_set(/*include_pipelines=*/false);

		width = width > g_state.width ? width : g_state.width;
		height = height > g_state.height ? height : g_state.height;
	}

	if (g_state.root_signature == nullptr && !create_root_signature())
		return false;
	if (g_state.encode_pso == nullptr && !create_pipeline(g_nr_encode_dxbc,
			sizeof(g_nr_encode_dxbc), "CreateComputePipelineState(encode)", &g_state.encode_pso))
		return false;
	if (g_state.decode_pso == nullptr && !create_pipeline(g_nr_decode_dxbc,
			sizeof(g_nr_decode_dxbc), "CreateComputePipelineState(decode)", &g_state.decode_pso))
		return false;
	if (g_state.heap == nullptr && !create_resources(width, height))
		return false;

	STRAY_LOG_INFO("nr_codec ready: %ux%u FP16 proxy, engine image format %d (typed UAV "
		"load+store confirmed). DLSSNR.Color will be the PROXY, never the raw HDR image.",
		width, height, static_cast<int>(desc.Format));
	return true;
}

void set_timeline(const nrlife::Timeline &timeline) { g_state.timeline = timeline; }

void request_shutdown()
{
	// Destroys NOTHING. The live set moves into the graveyard tagged against the current
	// timeline, and collect() frees it at a present the GPU has passed. This is the call the
	// NgxNR 1->0 toggle and the ini reloader make, from whatever thread they happen to be on.
	const bool had_anything = is_ready() || g_state.root_signature != nullptr;
	retire_live_set(/*include_pipelines=*/true);
	// The engine image and the neural texture we AddRef'd stay held until their own tags clear;
	// dropping them here would be the same defect in a different resource.
	g_state.width = 0;
	g_state.height = 0;
	g_state.image_format = DXGI_FORMAT_UNKNOWN;
	g_state.format_checked = false;
	if (had_anything)
		STRAY_LOG_INFO("nr_codec: teardown REQUESTED (%u set(s) now waiting on the GPU). Nothing "
			"is destroyed until a present whose fence has passed the work that referenced it.",
			static_cast<unsigned int>(g_state.retired.size()));
}

void collect()
{
	retire_expired();
	// The keep-alive list is drained by the same rule. Without a record this frame nothing else
	// would ever revisit it, so a disabled NR must still eventually release the engine's
	// textures — deferred is not the same as leaked.
	for (auto it = g_state.input_keep_alive.begin(); it != g_state.input_keep_alive.end();)
	{
		if (nrlife::safe_to_free(g_state.timeline, it->tag))
		{
			if (it->a != nullptr)
				it->a->Release();
			if (it->b != nullptr)
				it->b->Release();
			it = g_state.input_keep_alive.erase(it);
		}
		else
			++it;
	}
}

void shutdown()
{
	// IMMEDIATE. Only correct at device destruction, where the caller has already established
	// that nothing is executing. Say so if anything was still waiting, because that is the one
	// thing this call cannot check for itself.
	if (!g_state.retired.empty() || !g_state.input_keep_alive.empty())
		STRAY_LOG_WARN("nr_codec: immediate shutdown with %u retired set(s) and %u held input(s) "
			"still tagged against the GPU timeline. That is only safe at device destruction; "
			"anywhere else it means the deferred path (request_shutdown + collect) was skipped.",
			static_cast<unsigned int>(g_state.retired.size()),
			static_cast<unsigned int>(g_state.input_keep_alive.size()));

	for (auto &r : g_state.retired)
	{
		release(r.heap);
		release(r.constants);
		release(r.proxy);
		release(r.encode_pso);
		release(r.decode_pso);
		release(r.root_signature);
	}
	g_state.retired.clear();

	for (auto &li : g_state.input_keep_alive)
	{
		if (li.a != nullptr)
			li.a->Release();
		if (li.b != nullptr)
			li.b->Release();
	}
	g_state.input_keep_alive.clear();

	release(g_state.proxy);
	release(g_state.constants);
	release(g_state.heap);
	release(g_state.decode_pso);
	release(g_state.encode_pso);
	release(g_state.root_signature);
	g_state.device = nullptr;
	g_state.width = 0;
	g_state.height = 0;
	g_state.image_format = DXGI_FORMAT_UNKNOWN;
	g_state.format_checked = false;
	g_state.encoded_this_frame = false;
	g_state.stats.live_retired = 0;
	g_state.timeline = nrlife::Timeline{};
}

bool record_encode(ID3D12GraphicsCommandList *cmd, ID3D12Resource *image, std::uint32_t width,
                   std::uint32_t height, float scale, float color_strength,
                   float transfer_strength)
{
	g_state.encoded_this_frame = false;
	if (cmd == nullptr || image == nullptr || !is_ready() || width == 0 || height == 0)
		return false;

	// Never dispatch past what we allocated: the grow-only policy means the proxy is at least
	// as large as this frame, but a caller bug must not become an out-of-bounds UAV write.
	if (width > g_state.width)
		width = g_state.width;
	if (height > g_state.height)
		height = g_state.height;

	const UINT slot = ring::slot_for_frame(g_state.frame);
	++g_state.frame;

	retire_expired();
	keep_alive(image, nullptr);

	// One constants write per frame, before the encode: the decode reads the same slot and
	// nothing between the two changes any of these values.
	Params params = {};
	params.image_size[0] = width;
	params.image_size[1] = height;
	params.scale = scale;
	params.color_strength = color_strength;
	params.transfer_strength = transfer_strength;

	void *mapped = nullptr;
	D3D12_RANGE no_read = { 0, 0 };
	if (FAILED(g_state.constants->Map(0, &no_read, &mapped)) || mapped == nullptr)
	{
		set_error_text("record_encode: could not map the constant buffer");
		return false;
	}
	const std::size_t cb_offset = ring::constant_offset(slot, g_state.constant_stride);
	std::memcpy(static_cast<std::uint8_t *>(mapped) + cb_offset, &params, sizeof(params));
	D3D12_RANGE written = { cb_offset, cb_offset + sizeof(params) };
	g_state.constants->Unmap(0, &written);

	write_uav(slot, kEncodeBase, 0, image, g_state.image_format);
	write_uav(slot, kEncodeBase, 1, g_state.proxy, kProxyFormat);
	write_null_uav(slot, kEncodeBase, 2);

	// The SR/RR evaluate wrote `image` through its own UAV; make those stores visible to us.
	uav_barrier(cmd, image, nullptr);

	bind_common(cmd, slot, kEncodeBase, g_state.encode_pso);
	cmd->Dispatch((width + 7) / 8, (height + 7) / 8, 1);

	// NGX reads the proxy right afterwards.
	uav_barrier(cmd, g_state.proxy, nullptr);

	g_state.current_slot = slot;
	g_state.encoded_this_frame = true;
	return true;
}

void transition_proxy(ID3D12GraphicsCommandList *cmd, bool to_shader_resource)
{
	if (cmd == nullptr || g_state.proxy == nullptr)
		return;

	D3D12_RESOURCE_BARRIER barrier = {};
	barrier.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
	barrier.Transition.pResource = g_state.proxy;
	barrier.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
	barrier.Transition.StateBefore = to_shader_resource
		? D3D12_RESOURCE_STATE_UNORDERED_ACCESS
		: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
	barrier.Transition.StateAfter = to_shader_resource
		? D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE
		: D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
	cmd->ResourceBarrier(1, &barrier);
}

bool record_decode(ID3D12GraphicsCommandList *cmd, ID3D12Resource *image,
                   ID3D12Resource *neural, std::uint32_t width, std::uint32_t height)
{
	if (cmd == nullptr || image == nullptr || neural == nullptr || !is_ready())
		return false;
	if (!g_state.encoded_this_frame)
	{
		// Without the encode's constants and its ring slot the decode would read another
		// frame's parameters. Refuse rather than transfer against a stale proxy.
		set_error_text("record_decode: no encode was recorded this frame");
		return false;
	}
	g_state.encoded_this_frame = false;

	if (width > g_state.width)
		width = g_state.width;
	if (height > g_state.height)
		height = g_state.height;

	const UINT slot = g_state.current_slot;
	keep_alive(neural, nullptr);

	write_uav(slot, kDecodeBase, 0, g_state.proxy, kProxyFormat);
	write_uav(slot, kDecodeBase, 1, neural, g_state.image_format);
	write_uav(slot, kDecodeBase, 2, image, g_state.image_format);

	// NGX has just written the neural texture through its own UAV; make those stores visible.
	uav_barrier(cmd, neural, nullptr);

	bind_common(cmd, slot, kDecodeBase, g_state.decode_pso);
	cmd->Dispatch((width + 7) / 8, (height + 7) / 8, 1);

	// The engine image becomes the next frame's TAA history (CLAUDE.md §2.9), so whoever reads
	// it next must see this write.
	uav_barrier(cmd, image, nullptr);
	return true;
}

} // namespace stray_dlss::nrp
