#include "nr_mask.hpp"

#include "log.hpp"
#include "nr_stage.hpp"

#include <d3d12.h>

#include <cstdio>
#include <cstring>
#include <mutex>
#include <vector>

#include <nr_mask.h> // g_nr_mask_dxbc, generated by fxc at build time

namespace stray_dlss::nrmask {
namespace {

// Retired resources are held for this many presents before release. Two full frame pipelines,
// the same conservative depth nr_stage uses, for the same reason: a dispatch recorded two frames
// ago may still be executing and we have no fence of our own here.
constexpr std::uint64_t kRetireDelay = 6;

// The dispatch tiling. Must match [numthreads(8,8,1)] in shaders/nr_mask.hlsl.
constexpr std::uint32_t kTileX = 8;
constexpr std::uint32_t kTileY = 8;

// float4 gValue + uint2 gExtent, as root 32-bit constants.
constexpr UINT kRootConstantCount = 6;

struct Live
{
	ID3D12Resource *texture = nullptr;
	ID3D12DescriptorHeap *heap = nullptr; // one shader-visible UAV
	std::uint32_t width = 0;
	std::uint32_t height = 0;
	DXGI_FORMAT format = DXGI_FORMAT_UNKNOWN;
	std::uint64_t bytes = 0;
	// What was last WRITTEN, not what was last asked for. `filled` false means the texture's
	// contents are undefined and it must not be bound.
	bool filled = false;
	float value[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
	// D3D12 cannot be asked what state a resource is in, but this one is ours from creation, so
	// we know it exactly rather than assuming it. That is the difference between this and the
	// back-buffer state constant nr_hook.cpp has to take on trust.
	D3D12_RESOURCE_STATES state = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
};

struct Retired
{
	ID3D12Resource *texture = nullptr;
	ID3D12DescriptorHeap *heap = nullptr;
	std::uint64_t frame = 0;
};

// Everything below is touched from the present thread only, EXCEPT shutdown() (device
// destruction) and set_format() (startup). One lock per present costs nothing and removes the
// need to reason about those exceptions.
std::mutex g_mutex;
ID3D12Device *g_device = nullptr;
ID3D12RootSignature *g_root = nullptr;
ID3D12PipelineState *g_pso = nullptr;
Live g_live;
std::vector<Retired> g_retired;
Stats g_stats;
int g_format = kDefaultMaskFormat;
int g_probed_format = -1;
nrmaskplan::FormatSupport g_probe;
char g_last_error[192] = "";

void set_error(const char *what, HRESULT hr)
{
	std::snprintf(g_last_error, sizeof(g_last_error), "nr_mask: %s failed (hr=0x%08X)", what,
		static_cast<unsigned int>(hr));
	STRAY_LOG_ERROR("%s", g_last_error);
}

template <typename T> void release(T *&p)
{
	if (p != nullptr)
	{
		p->Release();
		p = nullptr;
	}
}

std::uint32_t format_bytes(DXGI_FORMAT f)
{
	switch (static_cast<std::uint32_t>(f))
	{
	case 2:  return 16; // R32G32B32A32_FLOAT
	case 10: return 8;  // R16G16B16A16_FLOAT
	case 11: return 8;  // R16G16B16A16_UNORM
	case 28: return 4;  // R8G8B8A8_UNORM
	default: return 0;
	}
}

bool create_pipeline()
{
	if (g_root != nullptr && g_pso != nullptr)
		return true;

	D3D12_DESCRIPTOR_RANGE range = {};
	range.RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
	range.NumDescriptors = 1; // u0
	range.BaseShaderRegister = 0;
	range.OffsetInDescriptorsFromTableStart = 0;

	D3D12_ROOT_PARAMETER params[2] = {};
	params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
	params[0].Constants.ShaderRegister = 0; // b0
	params[0].Constants.Num32BitValues = kRootConstantCount;
	params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
	params[1].DescriptorTable.NumDescriptorRanges = 1;
	params[1].DescriptorTable.pDescriptorRanges = &range;

	D3D12_ROOT_SIGNATURE_DESC desc = {};
	desc.NumParameters = 2;
	desc.pParameters = params;
	desc.Flags = D3D12_ROOT_SIGNATURE_FLAG_NONE;

	ID3DBlob *blob = nullptr;
	ID3DBlob *errors = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(&desc, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &errors);
	if (FAILED(hr))
	{
		if (errors != nullptr)
		{
			STRAY_LOG_ERROR("nr_mask: root signature: %.*s",
				static_cast<int>(errors->GetBufferSize()),
				static_cast<const char *>(errors->GetBufferPointer()));
			errors->Release();
		}
		set_error("D3D12SerializeRootSignature", hr);
		return false;
	}
	if (errors != nullptr)
		errors->Release();

	hr = g_device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(),
		IID_PPV_ARGS(&g_root));
	blob->Release();
	if (FAILED(hr))
	{
		set_error("CreateRootSignature", hr);
		return false;
	}

	D3D12_COMPUTE_PIPELINE_STATE_DESC pso = {};
	pso.pRootSignature = g_root;
	pso.CS.pShaderBytecode = g_nr_mask_dxbc;
	pso.CS.BytecodeLength = sizeof(g_nr_mask_dxbc);
	hr = g_device->CreateComputePipelineState(&pso, IID_PPV_ARGS(&g_pso));
	if (FAILED(hr))
	{
		set_error("CreateComputePipelineState", hr);
		return false;
	}
	return true;
}

void retire_live(std::uint64_t frame)
{
	if (g_live.texture == nullptr && g_live.heap == nullptr)
		return;
	Retired r;
	r.texture = g_live.texture;
	r.heap = g_live.heap;
	r.frame = frame;
	g_retired.push_back(r);
	++g_stats.retired;
	g_stats.live_retired = static_cast<std::uint32_t>(g_retired.size());
	g_live = Live{};
}

void transition(ID3D12GraphicsCommandList *cmd, ID3D12Resource *res, D3D12_RESOURCE_STATES from,
                D3D12_RESOURCE_STATES to)
{
	if (res == nullptr || from == to)
		return;
	D3D12_RESOURCE_BARRIER b = {};
	b.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
	b.Transition.pResource = res;
	b.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
	b.Transition.StateBefore = from;
	b.Transition.StateAfter = to;
	cmd->ResourceBarrier(1, &b);
}

} // namespace

void set_format(int dxgi_format)
{
	std::lock_guard<std::mutex> lock(g_mutex);
	g_format = dxgi_format;
	g_probed_format = -1; // a new format needs a new verdict
	g_probe = nrmaskplan::FormatSupport{};
}

int format()
{
	std::lock_guard<std::mutex> lock(g_mutex);
	return g_format;
}

nrmaskplan::FormatSupport probe(ID3D12Device *device)
{
	std::lock_guard<std::mutex> lock(g_mutex);
	if (g_probed_format == g_format && g_probe.queried)
		return g_probe;

	const nrstage::TypedUavSupport t = nrstage::probe_typed_uav(device, g_format);
	g_probed_format = g_format;
	g_probe.queried = t.queried;
	g_probe.view = t.view;
	g_probe.store = t.store;
	STRAY_LOG_INFO("NR mask: typed-UAV probe on DXGI_FORMAT %d — queried=%d view=%d store=%d. "
		"The fill is a compute shader, so a format this device cannot STORE to would leave the "
		"mask uninitialised while the runtime sampled it anyway; that is what the gate refuses.",
		g_format, g_probe.queried ? 1 : 0, g_probe.view ? 1 : 0, g_probe.store ? 1 : 0);
	return g_probe;
}

bool ensure(ID3D12Device *device, std::uint32_t width, std::uint32_t height, std::uint64_t frame)
{
	if (device == nullptr || width == 0 || height == 0)
	{
		std::snprintf(g_last_error, sizeof(g_last_error),
			"nr_mask: ensure(device=%p %ux%u) has nothing to allocate",
			static_cast<void *>(device), width, height);
		return false;
	}

	std::lock_guard<std::mutex> lock(g_mutex);

	if (g_device != nullptr && g_device != device)
	{
		// A new device means every handle we hold belongs to a dead one. Drop them without
		// releasing through the old device's objects.
		g_live = Live{};
		g_retired.clear();
		g_root = nullptr;
		g_pso = nullptr;
	}
	g_device = device;

	const auto fmt = static_cast<DXGI_FORMAT>(g_format);
	if (g_live.texture != nullptr && g_live.width == width && g_live.height == height
		&& g_live.format == fmt)
		return true;

	if (!create_pipeline())
		return false;

	// Anything already live describes a different rect or format. Retire, never release: a fill
	// recorded a frame or two ago may still be reading it, and so may an evaluate.
	retire_live(frame);

	D3D12_DESCRIPTOR_HEAP_DESC heap_desc = {};
	heap_desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
	heap_desc.NumDescriptors = 1;
	heap_desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
	ID3D12DescriptorHeap *heap = nullptr;
	HRESULT hr = device->CreateDescriptorHeap(&heap_desc, IID_PPV_ARGS(&heap));
	if (FAILED(hr))
	{
		set_error("CreateDescriptorHeap", hr);
		return false;
	}

	D3D12_HEAP_PROPERTIES props = {};
	props.Type = D3D12_HEAP_TYPE_DEFAULT;

	D3D12_RESOURCE_DESC tex = {};
	tex.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
	tex.Width = width;
	tex.Height = height;
	// A MIPPED input to feature 18 is a documented DXGI_ERROR_DEVICE_HUNG a few seconds later
	// rather than an error return, and this texture is one of its inputs. Single mip, single
	// slice, no MSAA, always — never inherited from anything (CLAUDE.md, "Three ways to hand
	// feature 18 something that hangs the GPU").
	tex.DepthOrArraySize = 1;
	tex.MipLevels = 1;
	tex.Format = fmt;
	tex.SampleDesc.Count = 1;
	tex.Layout = D3D12_TEXTURE_LAYOUT_UNKNOWN;
	tex.Flags = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;

	ID3D12Resource *texture = nullptr;
	hr = device->CreateCommittedResource(&props, D3D12_HEAP_FLAG_NONE, &tex,
		D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, IID_PPV_ARGS(&texture));
	if (FAILED(hr))
	{
		heap->Release();
		set_error("CreateCommittedResource(control mask)", hr);
		return false;
	}

	D3D12_UNORDERED_ACCESS_VIEW_DESC uav = {};
	uav.Format = fmt;
	uav.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
	device->CreateUnorderedAccessView(texture, nullptr, &uav,
		heap->GetCPUDescriptorHandleForHeapStart());

	g_live.texture = texture;
	g_live.heap = heap;
	g_live.width = width;
	g_live.height = height;
	g_live.format = fmt;
	g_live.bytes = static_cast<std::uint64_t>(width) * height * format_bytes(fmt);
	g_live.filled = false;
	g_live.state = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
	++g_stats.created;
	g_stats.bytes = g_live.bytes;

	STRAY_LOG_INFO("NR mask: allocated a %ux%u DLSSNR.ControlMask in DXGI_FORMAT %d "
		"([STRAYDLSS] NgxNRMaskFormat), %llu bytes. The runtime does not inspect a caller's "
		"format on this path, so if the mask has an effect but the WRONG one, this number is the "
		"first thing to change.",
		width, height, g_format, static_cast<unsigned long long>(g_live.bytes));
	return true;
}

bool record_fill(ID3D12GraphicsCommandList *cmd, const nrmaskplan::Plan &plan)
{
	if (cmd == nullptr || plan.result != nrmaskplan::MaskResult::ok)
		return false;

	std::lock_guard<std::mutex> lock(g_mutex);
	if (g_live.texture == nullptr || g_pso == nullptr || g_root == nullptr)
		return false;
	if (g_live.width != plan.width || g_live.height != plan.height)
		return false; // ensure() has not caught up with this rect yet; never fill a stale extent

	const float want[4] = { plan.value_r, plan.value_g, plan.value_b, plan.value_a };
	if (g_live.filled && std::memcmp(g_live.value, want, sizeof(want)) == 0)
		return true; // already correct; no dispatch, no barriers, nothing recorded

	transition(cmd, g_live.texture, g_live.state, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
	g_live.state = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;

	ID3D12DescriptorHeap *heaps[] = { g_live.heap };
	cmd->SetDescriptorHeaps(1, heaps);
	cmd->SetComputeRootSignature(g_root);
	cmd->SetPipelineState(g_pso);

	// float4 gValue, then uint2 gExtent — the order in shaders/nr_mask.hlsl's cbuffer.
	UINT constants[kRootConstantCount];
	std::memcpy(&constants[0], want, sizeof(want));
	constants[4] = g_live.width;
	constants[5] = g_live.height;
	cmd->SetComputeRoot32BitConstants(0, kRootConstantCount, constants, 0);
	cmd->SetComputeRootDescriptorTable(1, g_live.heap->GetGPUDescriptorHandleForHeapStart());

	cmd->Dispatch((g_live.width + kTileX - 1) / kTileX, (g_live.height + kTileY - 1) / kTileY, 1);

	// NGX wants its inputs in NON_PIXEL_SHADER_RESOURCE, and the transition doubles as the
	// UAV-write barrier the evaluate needs.
	transition(cmd, g_live.texture, D3D12_RESOURCE_STATE_UNORDERED_ACCESS,
		D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
	g_live.state = D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;

	std::memcpy(g_live.value, want, sizeof(want));
	g_live.filled = true;
	++g_stats.fills;

	STRAY_LOG_INFO("NR mask: filled the %ux%u ControlMask with RGBA (%.3f, %.3f, %.3f, %.3f)%s. "
		"R is the per-pixel final blend weight, G scales local tone, B scales local structure; "
		"1.0 in every channel is the identity. Binding a mask AT ALL forces DLSSNR.UseAutoMask "
		"to 0 and drives both resolved structure strengths to -1.0 (src/core/nr_mask_plan.hpp), "
		"so this line changing the image is not by itself evidence that the mask VALUES did.",
		g_live.width, g_live.height, static_cast<double>(want[0]), static_cast<double>(want[1]),
		static_cast<double>(want[2]), static_cast<double>(want[3]),
		plan.is_identity ? " — the IDENTITY mask" : "");
	return true;
}

ID3D12Resource *texture()
{
	std::lock_guard<std::mutex> lock(g_mutex);
	return g_live.filled ? g_live.texture : nullptr;
}

void collect(std::uint64_t frame)
{
	std::lock_guard<std::mutex> lock(g_mutex);
	for (auto it = g_retired.begin(); it != g_retired.end();)
	{
		if (frame < it->frame + kRetireDelay)
		{
			++it;
			continue;
		}
		release(it->texture);
		release(it->heap);
		++g_stats.released;
		it = g_retired.erase(it);
	}
	g_stats.live_retired = static_cast<std::uint32_t>(g_retired.size());
}

void shutdown()
{
	std::lock_guard<std::mutex> lock(g_mutex);
	for (Retired &r : g_retired)
	{
		release(r.texture);
		release(r.heap);
		++g_stats.released;
	}
	g_retired.clear();
	release(g_live.texture);
	release(g_live.heap);
	g_live = Live{};
	release(g_pso);
	release(g_root);
	g_device = nullptr;
	g_stats.live_retired = 0;
	g_stats.bytes = 0;
}

const char *last_error() { return g_last_error; }

Stats stats()
{
	std::lock_guard<std::mutex> lock(g_mutex);
	Stats s = g_stats;
	s.value_r = g_live.value[0];
	s.value_g = g_live.value[1];
	s.value_b = g_live.value[2];
	s.value_a = g_live.value[3];
	s.filled = g_live.filled;
	return s;
}

} // namespace stray_dlss::nrmask
