#include "nr_model.hpp"

#include "log.hpp"
#include "nr_stage.hpp"

#include <d3d12.h>

#include <cstdio>
#include <cstring>
#include <mutex>
#include <vector>

#include <nr_downsample.h> // g_nr_downsample_dxbc, generated by fxc at build time
#include <nr_resolve.h>    // g_nr_resolve_dxbc

namespace stray_dlss::nrmodel {
namespace {

constexpr std::uint64_t kRetireDelay = 6; // presents; the same margin nr_mask and nr_stage use
constexpr std::uint32_t kTileX = 8;
constexpr std::uint32_t kTileY = 8;
constexpr DXGI_FORMAT kSmallFormat = DXGI_FORMAT_R16G16B16A16_FLOAT;
// Descriptor heap ring: the views on the FULL staging copy are rewritten per record (the
// staging resource can be replaced by a resize), and a heap the GPU may still be reading for
// an in-flight present must not be rewritten under it. kRetireDelay presents of slack covers
// the swapchain's depth.
constexpr std::uint32_t kHeapRing = 8;
constexpr UINT kDescriptorsPerHeap = 6;
// Heap layout: [0] SRV full   [1] UAV shown  [2] UAV model  (downsample)
//              [3] SRV shown  [4] SRV model  [5] UAV full   (resolve)
constexpr UINT kSlotSrvFull = 0, kSlotUavShown = 1, kSlotUavModel = 2;
constexpr UINT kSlotSrvShown = 3, kSlotSrvModel = 4, kSlotUavFull = 5;

struct Small
{
	ID3D12Resource *shown = nullptr;
	ID3D12Resource *model = nullptr;
	std::uint32_t width = 0;
	std::uint32_t height = 0;
	DXGI_FORMAT full_format = DXGI_FORMAT_UNKNOWN;
	// Both small textures share one state; record_downsample moves them to 0x40 and
	// record_resolve moves them back to UAV.
	D3D12_RESOURCE_STATES state = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
};
struct Retired
{
	ID3D12Resource *a = nullptr;
	ID3D12Resource *b = nullptr;
	std::uint64_t frame = 0;
};

std::mutex g_mutex;
ID3D12Device *g_device = nullptr;
ID3D12RootSignature *g_root_down = nullptr;
ID3D12RootSignature *g_root_resolve = nullptr;
ID3D12PipelineState *g_pso_down = nullptr;
ID3D12PipelineState *g_pso_resolve = nullptr;
ID3D12DescriptorHeap *g_heaps[kHeapRing] = {};
UINT g_descriptor_size = 0;
std::uint32_t g_heap_cursor = 0;
Small g_small;
std::vector<Retired> g_retired;
Stats g_stats;
char g_last_error[256] = "";

void set_error(const char *what, HRESULT hr)
{
	std::snprintf(g_last_error, sizeof(g_last_error), "%s hr=0x%08x", what,
		static_cast<unsigned int>(hr));
	STRAY_LOG_ERROR("nr_model: %s", g_last_error);
}

void release(ID3D12Resource *&r)
{
	if (r != nullptr)
	{
		r->Release();
		r = nullptr;
	}
}

void transition(ID3D12GraphicsCommandList *cmd, ID3D12Resource *res, D3D12_RESOURCE_STATES from,
                D3D12_RESOURCE_STATES to)
{
	if (res == nullptr || from == to)
		return;
	D3D12_RESOURCE_BARRIER b = {};
	b.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
	b.Transition.pResource = res;
	b.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
	b.Transition.StateBefore = from;
	b.Transition.StateAfter = to;
	cmd->ResourceBarrier(1, &b);
}

void uav_barrier(ID3D12GraphicsCommandList *cmd, ID3D12Resource *res)
{
	D3D12_RESOURCE_BARRIER b = {};
	b.Type = D3D12_RESOURCE_BARRIER_TYPE_UAV;
	b.UAV.pResource = res;
	cmd->ResourceBarrier(1, &b);
}

bool build_root(ID3D12Device *device, bool resolve, ID3D12RootSignature **out)
{
	// Downsample: b0 constants | table t0 | table u0-u1.
	// Resolve:    b0 constants | table t0-t1 | table u0, plus a static linear-clamp sampler.
	D3D12_DESCRIPTOR_RANGE srv = {};
	srv.RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
	srv.NumDescriptors = resolve ? 2 : 1;
	srv.BaseShaderRegister = 0;
	srv.OffsetInDescriptorsFromTableStart = 0;
	D3D12_DESCRIPTOR_RANGE uav = {};
	uav.RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
	uav.NumDescriptors = resolve ? 1 : 2;
	uav.BaseShaderRegister = 0;
	uav.OffsetInDescriptorsFromTableStart = 0;

	D3D12_ROOT_PARAMETER params[3] = {};
	params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
	params[0].Constants.ShaderRegister = 0;
	params[0].Constants.Num32BitValues = 8;
	params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
	params[1].DescriptorTable.NumDescriptorRanges = 1;
	params[1].DescriptorTable.pDescriptorRanges = &srv;
	params[2].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
	params[2].DescriptorTable.NumDescriptorRanges = 1;
	params[2].DescriptorTable.pDescriptorRanges = &uav;

	D3D12_STATIC_SAMPLER_DESC sampler = {};
	sampler.Filter = D3D12_FILTER_MIN_MAG_MIP_LINEAR;
	sampler.AddressU = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
	sampler.AddressV = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
	sampler.AddressW = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
	sampler.MaxLOD = D3D12_FLOAT32_MAX;
	sampler.ShaderRegister = 0;
	sampler.ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	D3D12_ROOT_SIGNATURE_DESC desc = {};
	desc.NumParameters = 3;
	desc.pParameters = params;
	desc.NumStaticSamplers = resolve ? 1 : 0;
	desc.pStaticSamplers = resolve ? &sampler : nullptr;
	desc.Flags = D3D12_ROOT_SIGNATURE_FLAG_NONE;

	ID3DBlob *blob = nullptr;
	ID3DBlob *errors = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(&desc, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &errors);
	if (FAILED(hr))
	{
		if (errors != nullptr)
		{
			STRAY_LOG_ERROR("nr_model: root signature: %.*s",
				static_cast<int>(errors->GetBufferSize()),
				static_cast<const char *>(errors->GetBufferPointer()));
			errors->Release();
		}
		set_error("D3D12SerializeRootSignature", hr);
		return false;
	}
	if (errors != nullptr)
		errors->Release();
	hr = device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(),
		IID_PPV_ARGS(out));
	blob->Release();
	if (FAILED(hr))
	{
		set_error("CreateRootSignature", hr);
		return false;
	}
	return true;
}

bool create_pipelines(ID3D12Device *device)
{
	if (g_pso_down != nullptr && g_pso_resolve != nullptr)
		return true;
	g_device = device;
	if (g_root_down == nullptr && !build_root(device, false, &g_root_down))
		return false;
	if (g_root_resolve == nullptr && !build_root(device, true, &g_root_resolve))
		return false;
	D3D12_COMPUTE_PIPELINE_STATE_DESC pso = {};
	pso.pRootSignature = g_root_down;
	pso.CS.pShaderBytecode = g_nr_downsample_dxbc;
	pso.CS.BytecodeLength = sizeof(g_nr_downsample_dxbc);
	HRESULT hr = device->CreateComputePipelineState(&pso, IID_PPV_ARGS(&g_pso_down));
	if (FAILED(hr))
	{
		set_error("CreateComputePipelineState(downsample)", hr);
		return false;
	}
	pso.pRootSignature = g_root_resolve;
	pso.CS.pShaderBytecode = g_nr_resolve_dxbc;
	pso.CS.BytecodeLength = sizeof(g_nr_resolve_dxbc);
	hr = device->CreateComputePipelineState(&pso, IID_PPV_ARGS(&g_pso_resolve));
	if (FAILED(hr))
	{
		set_error("CreateComputePipelineState(resolve)", hr);
		return false;
	}
	for (std::uint32_t i = 0; i < kHeapRing; ++i)
	{
		D3D12_DESCRIPTOR_HEAP_DESC hd = {};
		hd.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
		hd.NumDescriptors = kDescriptorsPerHeap;
		hd.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
		hr = device->CreateDescriptorHeap(&hd, IID_PPV_ARGS(&g_heaps[i]));
		if (FAILED(hr))
		{
			set_error("CreateDescriptorHeap", hr);
			return false;
		}
	}
	g_descriptor_size = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
	return true;
}

bool create_small(ID3D12Device *device, std::uint32_t width, std::uint32_t height,
	ID3D12Resource **out)
{
	D3D12_HEAP_PROPERTIES heap = {};
	heap.Type = D3D12_HEAP_TYPE_DEFAULT;
	D3D12_RESOURCE_DESC tex = {};
	tex.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
	tex.Width = width;
	tex.Height = height;
	tex.DepthOrArraySize = 1;
	tex.MipLevels = 1;
	tex.Format = kSmallFormat;
	tex.SampleDesc.Count = 1;
	tex.Layout = D3D12_TEXTURE_LAYOUT_UNKNOWN;
	tex.Flags = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;
	const HRESULT hr = device->CreateCommittedResource(&heap, D3D12_HEAP_FLAG_NONE, &tex,
		D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, IID_PPV_ARGS(out));
	if (FAILED(hr))
	{
		set_error("CreateCommittedResource(NR model texture)", hr);
		return false;
	}
	return true;
}

D3D12_CPU_DESCRIPTOR_HANDLE cpu(ID3D12DescriptorHeap *heap, UINT slot)
{
	D3D12_CPU_DESCRIPTOR_HANDLE h = heap->GetCPUDescriptorHandleForHeapStart();
	h.ptr += static_cast<SIZE_T>(slot) * g_descriptor_size;
	return h;
}
D3D12_GPU_DESCRIPTOR_HANDLE gpu(ID3D12DescriptorHeap *heap, UINT slot)
{
	D3D12_GPU_DESCRIPTOR_HANDLE h = heap->GetGPUDescriptorHandleForHeapStart();
	h.ptr += static_cast<UINT64>(slot) * g_descriptor_size;
	return h;
}

void write_srv(ID3D12DescriptorHeap *heap, UINT slot, ID3D12Resource *res, DXGI_FORMAT fmt)
{
	D3D12_SHADER_RESOURCE_VIEW_DESC d = {};
	d.Format = fmt;
	d.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
	d.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
	d.Texture2D.MipLevels = 1;
	g_device->CreateShaderResourceView(res, &d, cpu(heap, slot));
}
void write_uav(ID3D12DescriptorHeap *heap, UINT slot, ID3D12Resource *res, DXGI_FORMAT fmt)
{
	D3D12_UNORDERED_ACCESS_VIEW_DESC d = {};
	d.Format = fmt;
	d.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
	g_device->CreateUnorderedAccessView(res, nullptr, &d, cpu(heap, slot));
}

// The staging copy is R10G10B10A2_UNORM (or whatever the back buffer is); a typed UAV on it
// needs the plain format, which is what the plan's typed-UAV gate checked.
DXGI_FORMAT view_format(DXGI_FORMAT f)
{
	return f;
}

} // namespace

bool ensure(ID3D12Device *device, std::uint32_t width, std::uint32_t height, int full_format,
	std::uint64_t frame)
{
	if (device == nullptr || width == 0 || height == 0)
		return false;
	std::lock_guard<std::mutex> lock(g_mutex);
	if (!create_pipelines(device))
		return false;
	const auto ff = static_cast<DXGI_FORMAT>(full_format);
	if (g_small.shown != nullptr && g_small.width == width && g_small.height == height &&
		g_small.full_format == ff)
		return true;
	if (g_small.shown != nullptr || g_small.model != nullptr)
	{
		Retired r;
		r.a = g_small.shown;
		r.b = g_small.model;
		r.frame = frame;
		g_retired.push_back(r);
		g_small = Small{};
	}
	if (!create_small(device, width, height, &g_small.shown) ||
		!create_small(device, width, height, &g_small.model))
	{
		release(g_small.shown);
		release(g_small.model);
		g_small = Small{};
		return false;
	}
	g_small.width = width;
	g_small.height = height;
	g_small.full_format = ff;
	g_small.state = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
	g_stats.width = width;
	g_stats.height = height;
	g_stats.bytes = static_cast<std::uint64_t>(width) * height * 8u * 2u;
	STRAY_LOG_WARN("NR MODEL RESOLUTION: two %ux%u R16G16B16A16_FLOAT textures created (%llu "
		"bytes). Feature 18 will be shown an exact area-average of the frame at this size and "
		"only its difference is laid back on the full frame (matched residual). The full-frame "
		"format is %d, which the resolve writes through a typed UAV.",
		width, height, static_cast<unsigned long long>(g_stats.bytes), full_format);
	return true;
}

bool record_downsample(ID3D12GraphicsCommandList *cmd, ID3D12Resource *full,
	std::uint32_t full_width, std::uint32_t full_height)
{
	if (cmd == nullptr || full == nullptr)
		return false;
	std::lock_guard<std::mutex> lock(g_mutex);
	if (g_small.shown == nullptr || g_pso_down == nullptr)
		return false;
	ID3D12DescriptorHeap *heap = g_heaps[g_heap_cursor % kHeapRing];
	write_srv(heap, kSlotSrvFull, full, view_format(g_small.full_format));
	write_uav(heap, kSlotUavShown, g_small.shown, kSmallFormat);
	write_uav(heap, kSlotUavModel, g_small.model, kSmallFormat);

	// Small textures to UAV if the previous frame's resolve did not already put them there.
	transition(cmd, g_small.shown, g_small.state, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
	transition(cmd, g_small.model, g_small.state, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
	g_small.state = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;

	ID3D12DescriptorHeap *heaps[] = { heap };
	cmd->SetDescriptorHeaps(1, heaps);
	cmd->SetComputeRootSignature(g_root_down);
	cmd->SetPipelineState(g_pso_down);
	UINT constants[8] = { full_width, full_height, g_small.width, g_small.height, 0, 0, 0, 0 };
	cmd->SetComputeRoot32BitConstants(0, 8, constants, 0);
	cmd->SetComputeRootDescriptorTable(1, gpu(heap, kSlotSrvFull));
	cmd->SetComputeRootDescriptorTable(2, gpu(heap, kSlotUavShown));
	cmd->Dispatch((g_small.width + kTileX - 1) / kTileX, (g_small.height + kTileY - 1) / kTileY, 1);

	// Both small textures to 0x40: `model` is the state nr::apply assumes for its image, and
	// `shown` is read as an SRV by the resolve.
	transition(cmd, g_small.shown, D3D12_RESOURCE_STATE_UNORDERED_ACCESS,
		static_cast<D3D12_RESOURCE_STATES>(nrstage::kStagingRestState));
	transition(cmd, g_small.model, D3D12_RESOURCE_STATE_UNORDERED_ACCESS,
		static_cast<D3D12_RESOURCE_STATES>(nrstage::kStagingRestState));
	g_small.state = static_cast<D3D12_RESOURCE_STATES>(nrstage::kStagingRestState);
	++g_stats.downsamples;
	return true;
}

ID3D12Resource *model()
{
	std::lock_guard<std::mutex> lock(g_mutex);
	return g_small.model;
}
ID3D12Resource *shown()
{
	std::lock_guard<std::mutex> lock(g_mutex);
	return g_small.shown;
}

bool record_resolve(ID3D12GraphicsCommandList *cmd, ID3D12Resource *full,
	std::uint32_t full_width, std::uint32_t full_height, float transfer_strength)
{
	if (cmd == nullptr || full == nullptr)
		return false;
	std::lock_guard<std::mutex> lock(g_mutex);
	if (g_small.shown == nullptr || g_pso_resolve == nullptr)
		return false;
	ID3D12DescriptorHeap *heap = g_heaps[g_heap_cursor % kHeapRing];
	write_srv(heap, kSlotSrvShown, g_small.shown, kSmallFormat);
	write_srv(heap, kSlotSrvModel, g_small.model, kSmallFormat);
	write_uav(heap, kSlotUavFull, full, view_format(g_small.full_format));
	g_heap_cursor = (g_heap_cursor + 1) % kHeapRing;

	const auto rest = static_cast<D3D12_RESOURCE_STATES>(nrstage::kStagingRestState);
	transition(cmd, full, rest, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);

	ID3D12DescriptorHeap *heaps[] = { heap };
	cmd->SetDescriptorHeaps(1, heaps);
	cmd->SetComputeRootSignature(g_root_resolve);
	cmd->SetPipelineState(g_pso_resolve);
	UINT constants[8] = { full_width, full_height, g_small.width, g_small.height, 0, 0, 0, 0 };
	std::memcpy(&constants[4], &transfer_strength, sizeof(float));
	cmd->SetComputeRoot32BitConstants(0, 8, constants, 0);
	cmd->SetComputeRootDescriptorTable(1, gpu(heap, kSlotSrvShown));
	cmd->SetComputeRootDescriptorTable(2, gpu(heap, kSlotUavFull));
	cmd->Dispatch((full_width + kTileX - 1) / kTileX, (full_height + kTileY - 1) / kTileY, 1);
	uav_barrier(cmd, full);
	transition(cmd, full, D3D12_RESOURCE_STATE_UNORDERED_ACCESS, rest);

	// Back to their rest state for the next frame's downsample.
	transition(cmd, g_small.shown, g_small.state, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
	transition(cmd, g_small.model, g_small.state, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
	g_small.state = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
	++g_stats.resolves;
	return true;
}

void collect(std::uint64_t frame)
{
	std::lock_guard<std::mutex> lock(g_mutex);
	for (auto it = g_retired.begin(); it != g_retired.end();)
	{
		if (frame < it->frame + kRetireDelay)
		{
			++it;
			continue;
		}
		release(it->a);
		release(it->b);
		it = g_retired.erase(it);
	}
}

void shutdown()
{
	std::lock_guard<std::mutex> lock(g_mutex);
	release(g_small.shown);
	release(g_small.model);
	g_small = Small{};
	for (Retired &r : g_retired)
	{
		release(r.a);
		release(r.b);
	}
	g_retired.clear();
	for (std::uint32_t i = 0; i < kHeapRing; ++i)
		if (g_heaps[i] != nullptr)
		{
			g_heaps[i]->Release();
			g_heaps[i] = nullptr;
		}
	if (g_pso_down != nullptr) { g_pso_down->Release(); g_pso_down = nullptr; }
	if (g_pso_resolve != nullptr) { g_pso_resolve->Release(); g_pso_resolve = nullptr; }
	if (g_root_down != nullptr) { g_root_down->Release(); g_root_down = nullptr; }
	if (g_root_resolve != nullptr) { g_root_resolve->Release(); g_root_resolve = nullptr; }
	g_device = nullptr;
}

const char *last_error() { return g_last_error; }

Stats stats()
{
	std::lock_guard<std::mutex> lock(g_mutex);
	return g_stats;
}

} // namespace stray_dlss::nrmodel
